iluwatar/java-design-patterns

- builder/src/main/java/com/iluwatar/HairType.java
- command/src/main/java/com/iluwatar/Goblin.java
- command/src/main/java/com/iluwatar/InvisibilitySpell.java
- command/src/main/java/com/iluwatar/ShrinkSpell.java
- command/src/main/java/com/iluwatar/Wizard.java
- facade/src/main/java/com/iluwatar/DwarvenGoldmineFacade.java
- facade/src/main/java/com/iluwatar/DwarvenMineWorker.java
- mediator/src/main/java/com/iluwatar/Action.java
- mediator/src/main/java/com/iluwatar/PartyImpl.java
- mediator/src/main/java/com/iluwatar/PartyMemberBase.java
- observer/src/main/java/com/iluwatar/generic/Observer.java
- servant/src/main/java/com/iluwatar/App.java
- servant/src/main/java/com/iluwatar/King.java
- servant/src/main/java/com/iluwatar/Queen.java
- servant/src/main/java/com/iluwatar/Royalty.java
- service-locator/src/main/java/com/iluwatar/App.java
- service-locator/src/main/java/com/iluwatar/InitContext.java
- service-locator/src/main/java/com/iluwatar/Service.java
- service-locator/src/main/java/com/iluwatar/ServiceCache.java
- service-locator/src/main/java/com/iluwatar/ServiceImpl.java
- service-locator/src/main/java/com/iluwatar/ServiceLocator.java
Hi, I had changed for some patterns, please check.
> Makes a few improvements, basically unnecessary declarations, formatting

- .gitignore
- adapter/src/main/java/com/iluwatar/App.java
- command/src/main/java/com/iluwatar/App.java
- command/src/main/java/com/iluwatar/Command.java
- command/src/main/java/com/iluwatar/InvisibilitySpell.java
- command/src/main/java/com/iluwatar/ShrinkSpell.java
- command/src/main/java/com/iluwatar/Target.java
- command/src/main/java/com/iluwatar/Wizard.java
1. add redo function into command pattern.
2. add .iml and .idea into .gitignore
> add redo function into command pattern

- dao/src/main/java/com/iluwatar/App.java
fixes #53
Signed-off-by: Magesh Khanna Vadivelu <mvadivelu@turn.com>
> Documentation change in DAO pattern

- README.md
I have updated the README to use relative links for issue #180
> PR for #180 change links to relative

- README.md
Notes:
some lines had breaks at varying positions, fixed to 80.
this improves readability to me immensely
some stuff should not be wrapped and other parts are just hard to
wrap, so I am satisfied with this for now.
Solves #192 (partially, but enough for now).
[ci skip]
> Wrapping some parts of the README at 80 #192.

- README.md
Also reworded some sentences and wrapped one or two huge lines I would need to
change anyway.
Closes #192
> Better capitalization in the readme.

- README.md
Presently some of the sections such as FAQ, How to contribute were not easily accessible from the top of README. I didn't even realize they existed until I scrolled till very bottom. I think this navigation scheme provides easy access to all major sections of README.
> Provided better navigation in README

- README.md
This is continuation of #177 which implemented #109 
I totally forgot to add references in credits section and PR was merged and closed. GitHub does not allow reopening PRs so had to issue a new one.
> Added reference to POSA and white paper of pattern in README

- README.md
- _layouts/default.html
- static/js/index.js
Needs some peer review in the JS part. I used a cleaner solution and removed useless (chinese?) comments.
It wasn't working in Firefox 40 for me, so I guess it is a pretty big deal.
> Working back to top button.

- README.md
This helps non-GitHub experts to understand the process … :smile:
> Document automatic Jekyll process

- abstract-factory/src/main/java/com/iluwatar/abstractfactory/App.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/Army.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/Castle.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfArmy.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfCastle.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfKing.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/King.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcArmy.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcCastle.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcKing.java
- abstract-factory/src/test/java/com/iluwatar/abstractfactory/AppTest.java
The test classes printed to the console and didn't actually do any asserts so you could easily misread and think that it worked. By adding unit tests, it's very easy to see if there are any errors.
> Improved unit tests so assertions are used.

- README.md
I have added a Getting started section in README. I was thinking we should add more to this section guiding new comers on how to go about reading and understanding patterns.
We can introduce `Difficulty-Beginner`, `Difficulty-Intermediate`, `Difficulty-Expert`  tags and tag patterns based on their difficulty level so that beginners can have better clarity on which patterns should be read first. Do you think its a good idea @iluwatar @noobxgockel ?
> PR for Document design principles #208

- decorator/src/main/java/com/iluwatar/decorator/App.java
- decorator/src/main/java/com/iluwatar/decorator/Hostile.java
- decorator/src/main/java/com/iluwatar/decorator/SmartTroll.java
- decorator/src/main/java/com/iluwatar/decorator/Troll.java
As proposed on original description
> #247 adding getAttackPower method to pattern decorator

- singleton/src/main/java/com/iluwatar/singleton/App.java
- singleton/src/main/java/com/iluwatar/singleton/EnumIvoryTower.java
- singleton/src/main/java/com/iluwatar/singleton/InitializingOnDemandHolderIdiom.java
- singleton/src/main/java/com/iluwatar/singleton/IvoryTower.java
- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java
- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
This will eliminate all checkstyle warning according to checkstyle rules defined. Applicable just to singleton.
> Refactor singleton according to checkstyle rules

- lazy-loading/src/test/java/com/iluwatar/lazy/loading/HolderThreadSafeTest.java
- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
- singleton/src/test/java/com/iluwatar/singleton/LazyLoadedSingletonThreadSafetyTest.java
Add additional unit tests to show that singletons can be created in single thread environment and multithread environment. Also add a test to demonstrate a whole with Singleton when instantiating using reflection
(first ever pull request so if ive done something wrong or broken etiquette then apologies and let me know - thanks)
> Update to singleton unit tests and lazy loading unit test

- callback/src/main/java/com/iluwatar/callback/SimpleTask.java
- callback/src/test/java/com/iluwatar/callback/AppTest.java
add a unit test to callback pattern. Assert that the callback method is called using a counter
> Add unit test to callback method

- README.md
There is a lot of hype about design patterns, and this repository does not have a single KISS or YAGNI warning (at least I haven't seen one).
There is a lot of complex expositions of patterns that a beginner may think he or she must memorize before actually developing something slightly more complicated and no reminders beside the link in Getting Started that they are not mandatory. I thought we needed to have a paragraph directly oriented to DPs right on the readme. I think that that subsection would be the best place for it, but we can discuss that.
The text is adapted from [this (very related) post](http://blog.codinghorror.com/head-first-design-patterns/). Maybe we could even link to it somewhere.
> A Warning for beginners in the Readme.

- dao/src/test/java/com/iluwatar/dao/CustomerDaoImplTest.java
This is my first pull request ever. I'm so excited it's about a cult horror movie!
> Corrected Freddy's last name

- producer-consumer/src/test/java/com/iluwatar/producer/consumer/AppTest.java
> correct the package name for producer-consumer test folder

- abstract-factory/src/main/java/com/iluwatar/abstractfactory/App.java
I think it would be better to rename the App class to something like: Factory Producer. And the main method should be in the real App file as unique method. What do you think?
> Issue #286: Added main method in Abstract Factory Example

- repository/src/main/java/com/iluwatar/repository/AppConfig.java
- repository/src/test/java/com/iluwatar/repository/AnnotationBasedRepositoryTest.java
- repository/src/test/java/com/iluwatar/repository/AppConfigTest.java
Hi, every one. Hoswey I saw that you use Spring Data. Maybe is a good idea to use a Spring annotation based config too.
https://github.com/hoswey/java-design-patterns/pull/1/files
Please check
> Annotation Config was added.

- bridge/pom.xml
- bridge/src/test/java/com/iluwatar/bridge/BlindingMagicWeaponTest.java
- bridge/src/test/java/com/iluwatar/bridge/FlyingMagicWeaponTest.java
- bridge/src/test/java/com/iluwatar/bridge/MagicWeaponTest.java
- bridge/src/test/java/com/iluwatar/bridge/SoulEatingMagicWeaponTest.java
- builder/src/test/java/com/iluwatar/builder/HeroTest.java
- chain/src/main/java/com/iluwatar/chain/OrcCommander.java
- chain/src/main/java/com/iluwatar/chain/OrcOfficer.java
- chain/src/main/java/com/iluwatar/chain/OrcSoldier.java
- chain/src/main/java/com/iluwatar/chain/Request.java
- chain/src/test/java/com/iluwatar/chain/OrcKingTest.java
- decorator/pom.xml
- decorator/src/test/java/com/iluwatar/decorator/SmartTrollTest.java
- decorator/src/test/java/com/iluwatar/decorator/TrollTest.java
Added proper unit tests for chain, bridge and builder pattern #293
I did some minor modifications to the chain implementation, since there was nothing much to test. Request now has a method to check if someone in the chain handled it.
> Add proper unit tests for chain, bridge and builder pattern #293

- bridge/pom.xml
- composite/src/test/java/com/iluwatar/composite/MessengerTest.java
- decorator/pom.xml
- dependency-injection/pom.xml
- dependency-injection/src/test/java/com/iluwatar/dependency/injection/AdvancedWizardTest.java
- dependency-injection/src/test/java/com/iluwatar/dependency/injection/GuiceWizardTest.java
- dependency-injection/src/test/java/com/iluwatar/dependency/injection/SimpleWizardTest.java
- dependency-injection/src/test/java/com/iluwatar/dependency/injection/StdOutTest.java
- double-checked-locking/pom.xml
- double-checked-locking/src/main/java/com/iluwatar/doublechecked/locking/Inventory.java
- double-checked-locking/src/test/java/com/iluwatar/doublechecked/locking/InventoryTest.java
- double-dispatch/pom.xml
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/CollisionTest.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/FlamingAsteroidTest.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/MeteoroidTest.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/RectangleTest.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/SpaceStationIssTest.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/SpaceStationMirTest.java
- facade/pom.xml
- facade/src/test/java/com/iluwatar/facade/DwarvenGoldmineFacadeTest.java
Add proper unit tests for composite, dependency-injection, double-checked-locking, double-dispatch and facade. #293
> Added more JUnit tests

- caching/src/main/java/com/iluwatar/caching/App.java
- tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishSerializer.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - Dead stores should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1854
Kirill Vlasov
> Fixing squid:S1854 - Dead stores should be removed

- CONTRIBUTING.MD
so github will show link whenever PR are made
> add-contributing

- reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/App.java
- reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/Reader.java
- reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/Writer.java
- reader-writer-lock/src/test/java/com/iluwatar/reader/writer/lock/ReaderAndWriterTest.java
- reader-writer-lock/src/test/java/com/iluwatar/reader/writer/lock/ReaderTest.java
- reader-writer-lock/src/test/java/com/iluwatar/reader/writer/lock/StdOutTest.java
- reader-writer-lock/src/test/java/com/iluwatar/reader/writer/lock/WriterTest.java
fix issue #343 ReaderWriterLock unit tests fail on CI
> fix issue #343 ReaderWriterLock unit tests fail on CI

- decorator/index.md
change decorator_1.png to decorator.png
> Fix the wrong uml .png name in decorator

- builder/src/main/java/com/iluwatar/builder/Hero.java
- dao/src/test/java/com/iluwatar/dao/CustomerTest.java
- step-builder/src/main/java/com/iluwatar/stepbuilder/Character.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:ConsecutiveAppendsShouldReuse
M-Ezzat
> pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse

- caching/src/main/java/com/iluwatar/caching/CacheStore.java
- caching/src/main/java/com/iluwatar/caching/LruCache.java
- chain/src/main/java/com/iluwatar/chain/Request.java
- fluentinterface/src/main/java/com/iluwatar/fluentinterface/fluentiterable/lazy/DecoratingIterator.java
- fluentinterface/src/main/java/com/iluwatar/fluentinterface/fluentiterable/lazy/LazyFluentIterable.java
- model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileLoader.java
- monostate/src/main/java/com/iluwatar/monostate/LoadBalancer.java
- producer-consumer/src/main/java/com/iluwatar/producer/consumer/Producer.java
- reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/ReaderWriterLock.java
- reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/Writer.java
- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
- twin/src/main/java/com/iluwatar/twin/BallItem.java
This pull request is focused on resolving occurrences of Sonar rule pmd:RedundantFieldInitializer - Redundant-Field-Initializer
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/coding_rules#q=pmd:RedundantFieldInitializer
M-Ezzat
> pmd:RedundantFieldInitializer - Redundant-Field-Initializer

- abstract-factory/src/main/java/com/iluwatar/abstractfactory/App.java
- abstract-factory/src/test/java/com/iluwatar/abstractfactory/AbstractFactoryTest.java
- factory-method/src/main/java/com/iluwatar/factory/method/App.java
- factory-method/src/test/java/com/iluwatar/factory/method/FactoryMethodTest.java
I have made a few changes to Factory and Abstract factory while I was understanding example for lambda implementation.
Changes:
- Removed raw type warning from test case
- Made factory method example more understandable by injecting dependency of `Blacksmith` from outside, that makes it closer to real application scenario where the exact implementation is injected from outside based on configuration or environment.
Let me know if we can improve this further or doubts
> Factory and Abstract Factory changes

- dao/src/main/java/com/iluwatar/dao/App.java
In Dao pattern DaoImpl object is created with reference to dao interface.
> Dao Pattern : Create object with reference to Interface

- strategy/src/main/java/com/iluwatar/strategy/MeleeStrategy.java
> Severe is not appropriate.

- chain/README.md
- intercepting-filter/README.md
Pull request regarding issue #463 (extended chain real word examples section)
> #463 Added javax.servlet.Filter to real world examples intercepting filter

- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java
Explains the dynamics that happen on each step for better understanding. Did this due to a PR #475
> Documented singleton double check idiom

- singleton/src/main/java/com/iluwatar/singleton/InitializingOnDemandHolderIdiom.java
- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
I have made minor code changes to the `singleton` module
- Remove one extra space from `public static ...`
- Change access level to `private` for `INSTANCE` (this is not strictly related to the pattern, but I think that it makes no sense to have the field public).
> Minor code changes

- abstract-factory/README.md
- adapter/README.md
- builder/README.md
- chain/README.md
- command/README.md
- decorator/README.md
- factory-method/README.md
- flyweight/README.md
- interpreter/README.md
- iterator/README.md
- mediator/README.md
- observer/README.md
- singleton/README.md
- state/README.md
- visitor/README.md
I have added most of the examples and left out a few that are debatable. I have left comments on SO question for OP to answer and when they are resolved we can then later on update our references as well.
> #211 Document GoF usages from Java API

- service-locator/README.md
- singleton/README.md
Fixes #436, #437. 
Lists drawbacks of the Service Locator and Singleton patterns.
> Adds criticism to a Service Locator and Singleton patterns.

- async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutor.java
- async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutorTest.java
There are 2 changes:
- Logic blocks optimized;
- Unused import removed.
> Cosmetic fixes in async-method-invocation

- README.md
Now that you've added the project on SonarQube.com, you can use the following badge on your README file!
> Add SonarQube.com badge

- model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileLoader.java
- queue-load-leveling/src/main/java/com/iluwatar/queue/load/leveling/ServiceExecutor.java
- service-layer/src/main/java/com/iluwatar/servicelayer/common/DaoBaseImpl.java
- service-layer/src/main/java/com/iluwatar/servicelayer/spell/SpellDaoImpl.java
- service-layer/src/main/java/com/iluwatar/servicelayer/spellbook/SpellbookDaoImpl.java
- service-layer/src/main/java/com/iluwatar/servicelayer/wizard/WizardDaoImpl.java
- tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishSerializer.java
Addresses SonarQube bugs of blocker severity. The issues can be seen here: https://sonarqube.com/component_issues?id=com.iluwatar%3Ajava-design-patterns#resolved=false|types=BUG|severities=BLOCKER
Fixes 6 of the 7 issues. The seventh is by design.
> #507 SonarQube blocker severity bugs

- abstract-factory/README.md
Added few more points in applicability and also some use cases and consequences.
> Few additions in README

- tls/README.md
Fixed minor punctuation and spelling while reading through applicability
> Update README.md punctuation and spelling

- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
Added null check in private constructor to prevent instantiating by Reflection call
> Updated ThreadSafeLazyLoadedivoryTower

- data-transfer-object/README.md
Issue: #348 
Pattern: Data Transfer Object
---
Add a missing Puml id to README.md
> #348 - Data Tranfer Object : Add Puml id to README.md.

- decorator/README.md
- decorator/src/main/java/com/iluwatar/decorator/App.java
Trolls should not be re-declared: if I had a troll called Zac, one day I
gave him a weapon.I can not because he now has a weapon called him
Trundle. He is still Zac.
> Delete duplicate declared objects:ClubbedTroll

- model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileLoader.java
- model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileSelectorPresenter.java
- model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileSelectorView.java
- mutex/src/test/java/com/iluwatar/mutex/AppTest.java
- semaphore/src/test/java/com/iluwatar/semaphore/AppTest.java
- throttling/src/main/java/com/iluwatar/throttling/timer/ThrottleTimerImpl.java
There are few checkstyles problems found in the  which are required to be fixed
> Fixes Checkstyle problems

- command/src/main/java/com/iluwatar/command/Size.java
- command/src/main/java/com/iluwatar/command/Visibility.java
- command/src/main/java/com/iluwatar/command/Wizard.java
This PR is related to #547 which seems not a question to me but removed unused enumerations to avoid misunderstanding.
> Removes unused size and visibility enumerations

- monostate/src/main/java/com/iluwatar/monostate/LoadBalancer.java
fixes #666 to make it threadsafe
BTW: Moved id to static initizalizer block since it used only here.
> added synchronized keyword to method that reads from server poll

- factory-method/src/test/java/com/iluwatar/factory/method/FactoryMethodTest.java
[A or An](https://www.a-or-an.com/a_an/axe)
> replace 'a' with 'an'

- README.md
* add CII Best Practices badge
* resolves https://github.com/iluwatar/java-design-patterns/issues/672
> add CII Best Practices badge

- cqrs/src/main/java/com/iluwatar/cqrs/domain/model/Author.java
- cqrs/src/main/java/com/iluwatar/cqrs/domain/model/Book.java
- cqrs/src/main/java/com/iluwatar/cqrs/dto/Author.java
- cqrs/src/main/java/com/iluwatar/cqrs/dto/Book.java
- data-mapper/src/main/java/com/iluwatar/datamapper/Student.java
- queue-load-leveling/src/main/java/com/iluwatar/queue/load/leveling/Message.java
- value-object/src/main/java/com/iluwatar/value/object/HeroStat.java
Removing all redundant super constructor calls,[issue 694](https://github.com/iluwatar/java-design-patterns/issues/694#issuecomment-355732137)
> Removing all redundant super constructor calls, issue 694.

- singleton/src/main/java/com/iluwatar/singleton/EnumIvoryTower.java
- just adds clarifying comments on enum based singleton
> Add thread safety comment on enum based singleton

- event-queue/src/main/java/com/iluwatar/event/queue/Audio.java
> Fix error comment with isServiceRunnign in Event Queue

- singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
Add missing requirements from #583 .
Signed-off-by: Igor C. A. de Lima <igorcadelima@gmail.com>
> Protect against instantiation via reflection

- multiton/src/main/java/com/iluwatar/multiton/App.java
- multiton/src/main/java/com/iluwatar/multiton/NazgulEnum.java
- multiton/src/test/java/com/iluwatar/multiton/NazgulEnumTest.java
Implements multiton with enum in file called NazgulEnum.java. Adds the enum example to App.java. Adds a test for the enum called NazgulEnumTest.java. If you could please let me know your thoughts then I would much appreciate that.
> My solution to issue #602. 

- adapter/src/main/java/com/iluwatar/adapter/Captain.java
- adapter/src/test/java/com/iluwatar/adapter/AdapterPatternTest.java
Captain and RowingBoat aren't interchangable. 
Captain, as a client, may have a method to use the boat, but it isn't needed that they share the same interface, as it makes the code more confusing.
> Captain is implementing RowingBoat - Adapter pattern

- monad/src/main/java/com/iluwatar/monad/App.java
Just fixed a little repetition in the javadoc comment.
> Fixed typo

- abstract-factory/README.md
- adapter/README.md
- bridge/README.md
- builder/README.md
- chain/README.md
- composite/README.md
- decorator/README.md
- facade/README.md
- factory-method/README.md
- flyweight/README.md
- prototype/README.md
- proxy/README.md
- singleton/README.md
- Adds the `java` annotation to the code snippets in the README files for each pattern that has them.
- This will also update the site pages when applied with changes on the gh-pages branch (PR incoming)
> Add Java annotation to code blocks in README files #728

- reactor/src/main/java/com/iluwatar/reactor/framework/NioReactor.java
- reactor/src/main/java/com/iluwatar/reactor/framework/NioServerSocketChannel.java
Cleanup unnecessary code of Reactor pattern.
> Cleanup unnecessary code

- reactor/src/main/java/com/iluwatar/reactor/app/AppClient.java
Add an annotation 'Override' to mothod 'AppClient.TcpLoggingClient#run'.
> Add an 'Override' annotaion

- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/ZoomVisitor.java
- retry/src/main/java/com/iluwatar/retry/Retry.java
Fixed minor changes suggested by the Checkstyle guidelines.
> Fixed minor changes suggested by Checkstyle

- execute-around/src/main/java/com/iluwatar/execute/around/SimpleFileWriter.java
This pull request was created automatically as part of our ongoing efforts
at https://diffblue.com to implement refactorings. Feel free to leave feedback
here or contact us directly for any enquiries.
The developer in charge is @krobelus.
**Changes**:
- Replace try statements that close a resource in the finally block with a
try-with-resources statement [1].
[1] https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
> Use try-with-resources

- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/AllModemVisitor.java
- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/ConfigureForUnixVisitor.java
- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/Hayes.java
- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/Zoom.java
- Removed unchecked cast from acyclic visitor and used instanceof instead
- Improved javadocs a bit
> #781 Resolved ClasscastException from Acyclic Visitor

- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryNumbers.java
Fix redundant list alloc in LotteryNumbers
> Fix redundant list alloc in LotteryNumbers

- decorator/README.md
- decorator/src/main/java/com/iluwatar/decorator/App.java
- decorator/src/test/java/com/iluwatar/decorator/ClubbedTrollTest.java
- decorator/src/test/java/com/iluwatar/decorator/SimpleTrollTest.java
- strategy/src/test/java/com/iluwatar/strategy/DragonSlayerTest.java
- Remove redundant Exception from throws list in unit tests.
- If we assign new clubberTroll instance with the same variable, it will be wrapped by itself.
> Fix small points in Strategy and Decorator pattern.

- module/src/main/java/com/iluwatar/module/App.java
We don't need declare App class of module pattern as a utility class.
> No Need declare App class of module pattern as a utility class

- pom.xml
- spatial-partition/README.md
- spatial-partition/pom.xml
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/App.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Bubble.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Point.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/QuadTree.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Rect.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionBubbles.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionGeneric.java
- spatial-partition/src/test/java/com/iluwatar/spatialpartition/BubbleTest.java
- spatial-partition/src/test/java/com/iluwatar/spatialpartition/QuadTreeTest.java
- spatial-partition/src/test/java/com/iluwatar/spatialpartition/RectTest.java
- spatial-partition/src/test/java/com/iluwatar/spatialpartition/SpatialPartitionBubblesTest.java
Spatial partition pattern implementation
> Spatial partition pattern #562

- facade/src/main/java/com/iluwatar/facade/DwarvenMineWorker.java
> removed unnecessary static modifier on enum definition

- faq.md
- Added the FAQ in faq.md
- https://github.com/iluwatar/java-design-patterns/issues/756
- Faq added
> 756 : faq added

- spatial-partition/src/main/java/com/iluwatar/spatialpartition/QuadTree.java
- unnecessary if-else-return deleted
- https://github.com/iluwatar/java-design-patterns/issues/845
- unnecessary if-else-return deleted
> 845 : unneccesary return deleted

- README.md
Two sentences read a little awkward, so I tweaked them.
1) "Design patterns are **formalized best practices that the** programmer can use" -> "Design patterns are **the best formalized practices a** programmer can use"
2) "Reusing design patterns **helps to prevent subtle issues that can** cause major" -> "Reusing design patterns **help prevent subtle issues which** cause major
Hope this helps!
> Minor ReadMe Update

- chain/src/main/java/com/iluwatar/chain/OrcCommander.java
- chain/src/main/java/com/iluwatar/chain/OrcOfficer.java
- chain/src/main/java/com/iluwatar/chain/OrcSoldier.java
Dear all,
Should we apply best practice when compare enum in this case?
Reference: https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals
Thanks,
> Best practice when compare enum

- api-gateway/api-gateway-service/pom.xml
Fix the dependency conflict issue #868
> Fix the dependency conflict issue

- converter/src/main/java/com/iluwatar/converter/Converter.java
Typo coresponding -> corresponding
> Typo coresponding -> corresponding

- repository/README.md
Added one more credit/article about the benefits of Repository pattern
- added a thread from Stack Overflow about the benefits of Repository Pattern
> Added one more credit/article in Repository Pattern

- dirty-flag/src/main/java/com/iluwatar/dirtyflag/App.java
Bug fix for (#883 )
- fixed | Pass same instance "World" object for schedule Job 
- Create single instance "World" object for schedule Job. 
> fixed bug #883

- ambassador/README.md
Fix code example in Ambassador pattern
- Fixed syntax error in code example in README
> fix code example containing syntax error

- abstract-document/src/main/java/com/iluwatar/abstractdocument/AbstractDocument.java
Use functional style code and direct `foreach` instead of `entrySet` one.
> Use Functional style code [abstract-document]

- half-sync-half-async/README.md
- intercepting-filter/README.md
Pull request title :
Fix broken links
#915
Pull request description : 
1. Changed the link of BSD Unix networking subsystem (In Real world examples and Credits in half-sync-half-async/README.md)
2. Changed the link of Struts 2 - Interceptors (In intercepting-filter/README.md)
3. Removed the credits of Presentation Tier Patterns from Javagyan tutorial as Javagyan does not seem to be available now.
> Fix broken links #915

- adapter/README.md
Doc update for Adapter pattern
- Updating doc for Adapter pattern, where the doc shows different code from src code.
- This should resolve issue#925
- This pull request contains cosmetic change in README.md file only for ADAPTER pattern
> Updating README.md file to update doc as suggested in issue#925

- async-method-invocation/pom.xml
- bytecode/src/main/java/com/iluwatar/bytecode/Instruction.java
- caching/pom.xml
- caching/src/main/java/com/iluwatar/caching/CachingPolicy.java
- commander/src/main/java/com/iluwatar/commander/Commander.java
- commander/src/main/java/com/iluwatar/commander/queue/Queue.java
- double-checked-locking/src/main/java/com/iluwatar/doublechecked/locking/App.java
- event-asynchronous/src/main/java/com/iluwatar/event/asynchronous/Event.java
- exclude-pmd.properties
- flux/src/main/java/com/iluwatar/flux/action/Content.java
- half-sync-half-async/pom.xml
- hexagonal/src/main/java/com/iluwatar/hexagonal/service/ConsoleLottery.java
- naked-objects/pom.xml
- poison-pill/src/main/java/com/iluwatar/poison/pill/Message.java
- pom.xml
- retry/src/test/java/com/iluwatar/retry/RetryTest.java
- semaphore/src/main/java/com/iluwatar/semaphore/Fruit.java
- service-layer/src/main/java/com/iluwatar/servicelayer/common/BaseEntity.java
- trampoline/pom.xml
Fixes upgrade of maven plugins #943 
Some general code cleanup was necessary due to upgrade of PMD and checkstyle.
Also needed to add Junit 4 as a dependency due to Mockito.timout issue found here:
https://github.com/mockito/mockito/issues/152
> Upgrade of maven plugins

- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInformationClientImpl.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInventoryClientImpl.java
Issue: 
Exception Handling code in Aggregator Microservices module was not complete.
Changes: 
Handle ClientProtocolException and update error log messages.
> Fix for Issue #549 : Update Exception Handling Code in Aggregator Microservice

- pom.xml
Update dependencies reported by FDU Software Engineering Lab
> update buggy dependencies fixes #838

- pipeline/README.md
- pipeline/pom.xml
- pipeline/src/main/java/com.iluwatar.pipeline/App.java
- pipeline/src/main/java/com.iluwatar.pipeline/ConvertToCharArrayHandler.java
- pipeline/src/main/java/com.iluwatar.pipeline/Handler.java
- pipeline/src/main/java/com.iluwatar.pipeline/Pipeline.java
- pipeline/src/main/java/com.iluwatar.pipeline/RemoveAlphabetsHandler.java
- pipeline/src/main/java/com.iluwatar.pipeline/RemoveDigitsHandler.java
- pipeline/src/test/java/com.iluwatar.pipeline/AppTest.java
- pipeline/src/test/java/com.iluwatar.pipeline/PipelineTest.java
- pom.xml
A sample implementation of the pipeline pattern.
Resources:
* [The Pipeline Pattern — for fun and profit](https://medium.com/@aaronweatherall/the-pipeline-pattern-for-fun-and-profit-9b5f43a98130)
* [The Pipeline design pattern (in Java)](https://medium.com/@deepakbapat/the-pipeline-design-pattern-in-java-831d9ce2fe21)
* [Pipelines | Microsoft Docs](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff963548(v=pandp.10))
> #496 Pipeline pattern

- repository/src/main/resources/logback.xml
Changes: Repaired logging in Repository design pattern, to print logs into the console.
> Fix for issue #969: Repair logging in Repository design pattern

- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/Aggregator.java
- api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/ApiGateway.java
- naked-objects/webapp/src/main/webapp/about/index.html
Fixed all of the SonarCloud blocking errors. 
The errors included:
- "@RequestMapping" methods should specify HTTP method
- Links with "target=_blank" should prevent phishing attacks
These changes are the recommended changes by SonarCube for each of the above problems.
> 1011: Fixed all of the SonarCloud blocking errors

- hexagonal/src/main/java/com/iluwatar/hexagonal/sampledata/SampleData.java
- typeobjectpattern/src/main/java/com/iluwatar/typeobject/CellPool.java
The two remaining files were still creating a Random every time the method
was called. These were missed in the previous commit because the previous
commit had fixed only one of the methods; in other words, there were
multiple methods that were creating the Random object on each call.
> 1010: Fixed the two remaining SonarCloud errors

- abstract-document/src/main/java/com/iluwatar/abstractdocument/AbstractDocument.java
- abstract-document/src/main/java/com/iluwatar/abstractdocument/App.java
- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/App.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ConfigureForDosVisitorTest.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ConfigureForUnixVisitorTest.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/HayesTest.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ZoomTest.java
- adapter/src/main/java/com/iluwatar/adapter/App.java
- adapter/src/test/java/com/iluwatar/adapter/AdapterPatternTest.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/Aggregator.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInformationClientImpl.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInventoryClientImpl.java
#984 var changes for 
abstract-document
abstract-factory
acyclic-visitor
adapter
aggregator-microservices
Added var for local variables in cases var is improving readability
> #984 local variable inference changes

- README.md
> improve grammar of README

- serverless/src/main/java/com/iluwatar/serverless/baas/model/Person.java
- serverless/src/main/java/com/iluwatar/serverless/faas/ApiGatewayResponse.java
- serverless/src/main/java/com/iluwatar/serverless/faas/LambdaInfo.java
- serverless/src/main/java/com/iluwatar/serverless/faas/api/LambdaInfoApiHandler.java
> local variable type inference changes

- service-layer/src/main/java/com/iluwatar/servicelayer/app/App.java
- service-layer/src/main/java/com/iluwatar/servicelayer/common/DaoBaseImpl.java
- service-layer/src/main/java/com/iluwatar/servicelayer/magic/MagicServiceImpl.java
- service-layer/src/main/java/com/iluwatar/servicelayer/spell/SpellDaoImpl.java
- service-layer/src/main/java/com/iluwatar/servicelayer/spellbook/SpellbookDaoImpl.java
local variable type inference for service-layer design patterns
> service-layer local type inference changes

- state/src/main/java/com/iluwatar/state/App.java
local variable infere changes for STATE design pattern
> local variable infere changes

- tolerant-reader/src/main/java/com/iluwatar/tolerantreader/App.java
- tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishSerializer.java
- twin/src/main/java/com/iluwatar/twin/App.java
- unit-of-work/src/main/java/com/iluwatar/unitofwork/App.java
> #984 for unitofwork, tolerantreader, twin

- role-object/README.md
- role-object/pom.xml
- role-object/src/main/java/com/iluwatar/roleobject/ApplicationRoleObject.java
- role-object/src/main/java/com/iluwatar/roleobject/BorrowerRole.java
- role-object/src/main/java/com/iluwatar/roleobject/Customer.java
- role-object/src/main/java/com/iluwatar/roleobject/CustomerCore.java
- role-object/src/main/java/com/iluwatar/roleobject/CustomerRole.java
- role-object/src/main/java/com/iluwatar/roleobject/InvestorRole.java
- role-object/src/main/java/com/iluwatar/roleobject/Role.java
- role-object/src/test/java/com/iluwatar/roleobject/ApplicationRoleObjectTest.java
- role-object/src/test/java/com/iluwatar/roleobject/BorrowerRoleTest.java
- role-object/src/test/java/com/iluwatar/roleobject/CustomerCoreTest.java
- role-object/src/test/java/com/iluwatar/roleobject/InvestorRoleTest.java
- role-object/src/test/java/com/iluwatar/roleobject/RoleTest.java
The pattern Role object
Based on https://github.com/iluwatar/java-design-patterns/issues/862
> The pattern Role object

- abstract-document/src/main/java/com/iluwatar/abstractdocument/App.java
- abstract-document/src/test/java/com/iluwatar/abstractdocument/AbstractDocumentTest.java
- abstract-document/src/test/java/com/iluwatar/abstractdocument/DomainTest.java
- collection-pipeline/src/test/java/com/iluwatar/collectionpipeline/AppTest.java
- commander/src/main/java/com/iluwatar/commander/Service.java
- commander/src/main/java/com/iluwatar/commander/queue/QueueDatabase.java
- commander/src/test/java/com/iluwatar/commander/RetryTest.java
- composite/README.md
- composite/src/main/java/com/iluwatar/composite/Messenger.java
- converter/src/main/java/com/iluwatar/converter/App.java
- converter/src/test/java/com/iluwatar/converter/ConverterTest.java
Add java 11 support for #987
Added Convenience Factory Methods, unmodifiable collections
> Add java 11 support for #987 (a-c)

- dao/src/main/java/com/iluwatar/dao/App.java
- double-dispatch/src/main/java/com/iluwatar/doubledispatch/App.java
- facade/README.md
- facade/src/main/java/com/iluwatar/facade/DwarvenGoldmineFacade.java
- flyweight/src/main/java/com/iluwatar/flyweight/AlchemistShop.java
Add java 11 support for #987
Added Convenience Factory Methods, unmodifiable collections
> Add java 11 support for #987 (d-f)

- hexagonal/src/main/java/com/iluwatar/hexagonal/sampledata/SampleData.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/service/LotteryConsoleServiceImpl.java
- hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryNumbersTest.java
- hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTest.java
- hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTicketTest.java
- hexagonal/src/test/java/com/iluwatar/hexagonal/test/LotteryTestUtils.java
- iterator/src/main/java/com/iluwatar/iterator/list/TreasureChest.java
- iterator/src/test/java/com/iluwatar/iterator/list/TreasureChestTest.java
- layers/src/test/java/com/iluwatar/layers/CakeTest.java
- layers/src/test/java/com/iluwatar/layers/CakeViewImplTest.java
- leader-election/src/test/java/com/iluwatar/leaderelection/bully/BullyMessageManagerTest.java
- leader-election/src/test/java/com/iluwatar/leaderelection/ring/RingMessageManagerTest.java
Add java 11 support for #987
Added Convenience Factory Methods, unmodifiable collections
> Add java 11 support for #987 (h-l)

- callback/src/main/java/com/iluwatar/callback/App.java
- callback/src/main/java/com/iluwatar/callback/Callback.java
- callback/src/main/java/com/iluwatar/callback/LambdasApp.java
- callback/src/main/java/com/iluwatar/callback/SimpleTask.java
- callback/src/main/java/com/iluwatar/callback/Task.java
- callback/src/main/java/com/iluwatar/callback/package-info.java
decrease number of checkstyle errors in callback pattern
> https://github.com/iluwatar/java-design-patterns/issues/1021 - decrease number of checkstyle errors in callback pattern

- callback/src/main/java/com/iluwatar/callback/App.java
- callback/src/main/java/com/iluwatar/callback/Callback.java
- callback/src/main/java/com/iluwatar/callback/LambdasApp.java
- callback/src/main/java/com/iluwatar/callback/SimpleTask.java
- callback/src/main/java/com/iluwatar/callback/Task.java
- chain/src/main/java/com/iluwatar/chain/App.java
- chain/src/main/java/com/iluwatar/chain/OrcCommander.java
- chain/src/main/java/com/iluwatar/chain/OrcKing.java
- chain/src/main/java/com/iluwatar/chain/OrcOfficer.java
- chain/src/main/java/com/iluwatar/chain/OrcSoldier.java
- chain/src/main/java/com/iluwatar/chain/Request.java
- chain/src/main/java/com/iluwatar/chain/RequestHandler.java
- chain/src/main/java/com/iluwatar/chain/RequestType.java
- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/App.java
- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/CircuitBreaker.java
- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/DelayedService.java
- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/MonitoringService.java
- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/State.java
* callback
* chain
* circuit-breaker
- java docs
- indentations
- missing summary doc
> Resolves checkstyle errors for callback, chain, circuit-breaker

- converter/src/main/java/com/iluwatar/converter/App.java
- converter/src/main/java/com/iluwatar/converter/Converter.java
- converter/src/main/java/com/iluwatar/converter/User.java
- converter/src/main/java/com/iluwatar/converter/UserConverter.java
- converter/src/main/java/com/iluwatar/converter/UserDto.java
- cqrs/src/main/java/com/iluwatar/cqrs/app/App.java
- cqrs/src/main/java/com/iluwatar/cqrs/commandes/CommandServiceImpl.java
- cqrs/src/main/java/com/iluwatar/cqrs/commandes/ICommandService.java
- cqrs/src/main/java/com/iluwatar/cqrs/constants/AppConstants.java
- cqrs/src/main/java/com/iluwatar/cqrs/domain/model/Author.java
- cqrs/src/main/java/com/iluwatar/cqrs/domain/model/Book.java
- cqrs/src/main/java/com/iluwatar/cqrs/dto/Author.java
- cqrs/src/main/java/com/iluwatar/cqrs/dto/Book.java
- cqrs/src/main/java/com/iluwatar/cqrs/queries/IQueryService.java
- cqrs/src/main/java/com/iluwatar/cqrs/queries/QueryServiceImpl.java
- cqrs/src/main/java/com/iluwatar/cqrs/util/HibernateUtil.java
* converter
* cqrs
- java docs
- indentations
> Resolves checkstyle errors for converter, cqrs

- facade/src/main/java/com/iluwatar/facade/App.java
- facade/src/main/java/com/iluwatar/facade/DwarvenCartOperator.java
- facade/src/main/java/com/iluwatar/facade/DwarvenGoldDigger.java
- facade/src/main/java/com/iluwatar/facade/DwarvenGoldmineFacade.java
- facade/src/main/java/com/iluwatar/facade/DwarvenMineWorker.java
- facade/src/main/java/com/iluwatar/facade/DwarvenTunnelDigger.java
- factory-kit/src/main/java/com/iluwatar/factorykit/App.java
- factory-kit/src/main/java/com/iluwatar/factorykit/Axe.java
- factory-kit/src/main/java/com/iluwatar/factorykit/Bow.java
- factory-kit/src/main/java/com/iluwatar/factorykit/Spear.java
- factory-kit/src/main/java/com/iluwatar/factorykit/Sword.java
- factory-kit/src/main/java/com/iluwatar/factorykit/WeaponFactory.java
- factory-kit/src/main/java/com/iluwatar/factorykit/WeaponType.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/App.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Bubble.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Point.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/QuadTree.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Rect.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionBubbles.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionGeneric.java
- spatial-partition/src/test/java/com/iluwatar/spatialpartition/BubbleTest.java
- state/src/main/java/com/iluwatar/state/AngryState.java
- state/src/main/java/com/iluwatar/state/App.java
- state/src/main/java/com/iluwatar/state/Mammoth.java
- state/src/main/java/com/iluwatar/state/PeacefulState.java
- state/src/main/java/com/iluwatar/state/State.java
- step-builder/src/main/java/com/iluwatar/stepbuilder/App.java
- step-builder/src/main/java/com/iluwatar/stepbuilder/Character.java
- step-builder/src/main/java/com/iluwatar/stepbuilder/CharacterStepBuilder.java
* facade
* factory-kit
* spatial-partition
* state
* step-builder
- java docs
- indentations
> Resolves checkstyle errors for facade factory-kit spatial-partition state step-builder

- abstract-document/src/main/java/com/iluwatar/abstractdocument/AbstractDocument.java
- abstract-document/src/main/java/com/iluwatar/abstractdocument/App.java
- abstract-document/src/test/java/com/iluwatar/abstractdocument/AbstractDocumentTest.java
- abstract-document/src/test/java/com/iluwatar/abstractdocument/DomainTest.java
- abstract-factory/README.md
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/App.java
- abstract-factory/src/test/java/com/iluwatar/abstractfactory/AbstractFactoryTest.java
- abstract-factory/src/test/java/com/iluwatar/abstractfactory/AppTest.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/AppTest.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ConfigureForDosVisitorTest.java
- acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ConfigureForUnixVisitorTest.java
- adapter/README.md
- adapter/src/test/java/com/iluwatar/adapter/AdapterPatternTest.java
- adapter/src/test/java/com/iluwatar/adapter/AppTest.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/Aggregator.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInformationClientImpl.java
- aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInventoryClientImpl.java
- aggregator-microservices/aggregator-service/src/test/java/com/iluwatar/aggregator/microservices/AggregatorTest.java
- aggregator-microservices/information-microservice/src/test/java/com/iluwatar/information/microservice/InformationControllerTest.java
- aggregator-microservices/inventory-microservice/src/test/java/com/iluwatar/inventory/microservice/InventoryControllerTest.java
- api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/ApiGateway.java
- api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/ImageClientImpl.java
- api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/PriceClientImpl.java
- api-gateway/api-gateway-service/src/test/java/com/iluwatar/api/gateway/ApiGatewayTest.java
- api-gateway/image-microservice/src/test/java/com/iluwatar/image/microservice/ImageControllerTest.java
- api-gateway/price-microservice/src/test/java/com/iluwatar/price/microservice/PriceControllerTest.java
Migrates:
abstract-document
abstract-factory
acyclic-visitor
adapter
aggregator-microservices
api-gateway
> Java 11 migration: patterns starting with a

- specification/README.md
- specification/etc/specification.ucls
- specification/src/main/java/com/iluwatar/specification/app/App.java
- specification/src/main/java/com/iluwatar/specification/creature/AbstractCreature.java
- specification/src/main/java/com/iluwatar/specification/creature/Creature.java
- specification/src/main/java/com/iluwatar/specification/creature/Dragon.java
- specification/src/main/java/com/iluwatar/specification/creature/Goblin.java
- specification/src/main/java/com/iluwatar/specification/creature/Octopus.java
- specification/src/main/java/com/iluwatar/specification/creature/Shark.java
- specification/src/main/java/com/iluwatar/specification/creature/Troll.java
- specification/src/main/java/com/iluwatar/specification/property/Color.java
- specification/src/main/java/com/iluwatar/specification/property/Mass.java
- specification/src/main/java/com/iluwatar/specification/selector/MassGreaterThanSelector.java
- specification/src/main/java/com/iluwatar/specification/selector/MassSmallerThanOrEqSelector.java
- specification/src/test/java/com/iluwatar/specification/creature/CreatureTest.java
- specification/src/test/java/com/iluwatar/specification/selector/MassSelectorTest.java
In this pull request I propose a solution to Issue#1055 (https://github.com/iluwatar/java-design-patterns/issues/1055).
I added a couple of new selectors that can accept parameters, allowing for more flexibility in the use of this pattern. (See https://martinfowler.com/apsupp/spec.pdf). I modified the existing README with an example of how to use those new selectors, as well as explaining the difference with the existing Specification pattern.
I wrote unit tests following the same pattern as the ones already present. The code complies to Google Java Style Guide according to the Checkstyle plugin.
As I wrote in [this](https://github.com/iluwatar/java-design-patterns/issues/1055#issuecomment-553526646) comment, the UML diagram has not been updated yet.
Please do not hesitate to send me your …
> Adding parameterized specification (Issue#1055)

- decorator/src/main/java/com/iluwatar/decorator/App.java
As described in issue #1095, this pull request changes the description of the association between the decorator and its inner object. The current version states that this is an aggregation, but as explained in issue #1095 this should be a composition.
> Changes the description of the decorator pattern (as described in issue #1095)

- LICENSE.md
> LICENSE: Happy new year!

- collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/ImperativeProgramming.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
#1163 
> Fix imperative-style.

- module/src/main/java/com/iluwatar/module/App.java
- module/src/test/java/com/iluwatar/module/FileLoggerModuleTest.java
#984 Added Java 11 support for Module
- Added Java 11 support for Module and created constants in App.java for MESSAGE & ERROR
> #984 Added Java 11 support for Module

- service-layer/src/main/resources/logback.xml
- Fix broken logging in service layer
- #1339
- Changes in service-layer `logback.xml` to fix logging
> Fix broken logging in service layer

- naked-objects/dom/pom.xml
- naked-objects/dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.layout.json
- naked-objects/dom/src/main/java/domainapp/dom/modules/simple/SimpleObject.java
- naked-objects/dom/src/main/java/domainapp/dom/modules/simple/SimpleObject.layout.json
- naked-objects/dom/src/test/java/domainapp/dom/modules/simple/SimpleObjectTest.java
- naked-objects/dom/src/test/java/domainapp/dom/modules/simple/SimpleObjectsTest.java
- naked-objects/fixture/src/main/java/domainapp/fixture/modules/simple/SimpleObjectCreate.java
- naked-objects/fixture/src/main/java/domainapp/fixture/scenarios/RecreateSimpleObjects.java
- naked-objects/integtests/src/test/java/domainapp/integtests/bootstrap/SimpleAppSystemInitializer.java
- naked-objects/integtests/src/test/java/domainapp/integtests/specglue/CatalogOfFixturesGlue.java
- naked-objects/integtests/src/test/java/domainapp/integtests/specglue/modules/simple/SimpleObjectGlue.java
- naked-objects/integtests/src/test/java/domainapp/integtests/tests/modules/simple/SimpleObjectIntegTest.java
- naked-objects/integtests/src/test/java/domainapp/integtests/tests/modules/simple/SimpleObjectsIntegTest.java
- naked-objects/webapp/ide/eclipse/launch/.gitignore
- naked-objects/webapp/pom.xml
- naked-objects/webapp/src/main/java/domainapp/webapp/SimpleApplication.java
- naked-objects/webapp/src/main/webapp/about/index.html
- null-object/README.md
- null-object/src/main/java/com/iluwatar/nullobject/App.java
- null-object/src/test/java/com/iluwatar/nullobject/AppTest.java
- null-object/src/test/java/com/iluwatar/nullobject/NullNodeTest.java
- null-object/src/test/java/com/iluwatar/nullobject/TreeTest.java
Covers:
* null-object
* naked-object
> Java 11 remaining pattern

- module/src/test/java/com/iluwatar/module/FileLoggerModuleTest.java
Hello, noticed some minor spelling error in the comment in 
java-design-patterns\module\src\test\java\com\iluwatar\module\FileLoggerModuleTest.java
> Some minor spelling error in comment

- private-class-data/README.md
Explanation for Private class data pattern. Would like to have some comment.
> Private class data explanation

- api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/ImageClientImpl.java
- api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/PriceClientImpl.java
- api-gateway/image-microservice/src/main/java/com/iluwatar/image/microservice/ImageController.java
- api-gateway/price-microservice/src/main/java/com/iluwatar/price/microservice/PriceController.java
Logging in API Gateway
- Adds logging in api gateway to help in understanding the request flow.
- https://github.com/iluwatar/java-design-patterns/issues/1338
> Add logging in API Gateway

- singleton/src/main/java/com/iluwatar/singleton/InitializingOnDemandHolderIdiom.java
> fix word typo

- .github/workflows/maven-ci.yml
- .github/workflows/maven-pr-builder.yml
> Cleaning up unnecessary code from the CI yaml and CI server version upgrade

- zh/adapter/README.md
- zh/observer/README.md
- zh/strategy/README.md
- finish **Chinese translations** of adapter,observer and strategy pattern
> Translation zh

- .github/workflows/maven-ci.yml
> Cache SonarCloud packages

- README.md
Add missing word in README.md sentence.
> Add missing word to README.md

- iterator/README.md
This adds a link to a tutorial to the Iterator pattern: 
(http://www.tutorialspoint.com/java/java_using_iterator.htm)
> issue 525: attach tutorialspoint link to iterator pattern

- factory/README.md
> Word mistake in factory/README.md #1601

- game-loop/src/test/java/com/iluwatar/gameloop/AppTest.java
- game-loop/src/test/java/com/iluwatar/gameloop/FixedStepGameLoopTest.java
- game-loop/src/test/java/com/iluwatar/gameloop/FrameBasedGameLoopTest.java
- game-loop/src/test/java/com/iluwatar/gameloop/GameControllerTest.java
- game-loop/src/test/java/com/iluwatar/gameloop/GameLoopTest.java
- game-loop/src/test/java/com/iluwatar/gameloop/VariableStepGameLoopTest.java
Changing the import from JUnit4 to JUnit5
> JUnit4 to JUnit5

- factory/README.md
Real world examples added for Factory pattern.
> Factory pattern : Update README.md with Real world example

- README.md
Updated the CI badge for the new pipeline build that we use.
> update CI badge

- tr/singleton/README.md
#1625
Turkish translation is added for singleton design pattern
> #1625 add Turkish translation for singleton design pattern

- commander/src/main/java/com/iluwatar/commander/Order.java
- commander/src/main/java/com/iluwatar/commander/Retry.java
- commander/src/main/java/com/iluwatar/commander/Service.java
- event-asynchronous/src/main/java/com/iluwatar/event/asynchronous/EventManager.java
- game-loop/src/main/java/com/iluwatar/gameloop/GameLoop.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryNumbers.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/sampledata/SampleData.java
- leader-followers/src/main/java/com/iluwatar/leaderfollowers/App.java
- master-worker-pattern/src/main/java/com/iluwatar/masterworker/ArrayUtilityMethods.java
- producer-consumer/src/main/java/com/iluwatar/producer/consumer/Producer.java
- sharding/src/main/java/com/iluwatar/sharding/LookupShardManager.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/App.java
- spatial-partition/src/main/java/com/iluwatar/spatialpartition/Bubble.java
- typeobjectpattern/src/main/java/com/iluwatar/typeobject/CellPool.java
- update-method/src/main/java/com/iluwatar/updatemethod/World.java
As reported by SonarCloud use should use `SecureRandom()` instead of `Random()`
> updated Random() to SecureRandom()

- pom.xml
~**maven-checkstyle-plugin** from _`3.1.0`_ to _**`3.1.2`**_ 🆕~
> Use property to set version and update dependencies 

- active-object/src/main/java/com/iluwatar/activeobject/ActiveCreature.java
- active-object/src/main/java/com/iluwatar/activeobject/Orc.java
- active-object/src/test/java/com/iluwatar/activeobject/ActiveCreatureTest.java
- active-object/src/test/java/com/iluwatar/activeobject/AppTest.java
Added license headers to active object pattern
> refactor: added license headers to active object pattern

- factory/README.md
- fix spelling errors
- This Ferrari. -> This is Ferrari.
> fix spelling errors

- balking/README.md
- balking/src/main/java/com/iluwatar/balking/App.java
In this pull request, I continue adding the explanations for patterns (see #590).
- Add an explanation for the balking pattern
- Fix some grammar issues and typos
- Minor improvements to the source code
> Add explanation for balking pattern

- model-view-viewmodel/README.md
Noticed that after merging MVVM it has some display problems on the website https://java-design-patterns.com/patterns/model-view-viewmodel/. In this PR:
- Fixes minor problems in MVVM pattern `README.md` to display it correctly on the website
> Fix MVVM pattern readme

- caching/README.md
- caching/src/main/java/com/iluwatar/caching/AppManager.java
- caching/src/main/java/com/iluwatar/caching/DbManager.java
Continues the epic quest 🐉 of explaining each and all of the patterns #590. In this PR:
- Add explanation for caching pattern
- Light refactoring to update logging code
I think I'll also create a follow-up issue with some ideas about improving the code quality in this pattern.
> Add explanation for caching pattern

- .github/workflows/maven-ci.yml
- .github/workflows/maven-pr-builder.yml
Update `actions/setup-java` actions to **`'adopt'`**
@iluwatar Please add this to master on an urgent basis.
> update distribution for java to 'adpot'

- fr/README.md
Improve french translation.
The text has been profoundly rewritten, some parts were not understandable (or totally wrong).
> Improve french translation, fix some typographic issues.

- .github/workflows/maven-ci.yml
- .github/workflows/maven-pr-builder.yml
- reactor/src/main/java/com/iluwatar/reactor/app/App.java
- reactor/src/main/java/com/iluwatar/reactor/app/AppClient.java
> bug-fix: failing CI

- zh/async-method-invocation/README.md
Chinese translation of documents
Translated the async method invocation pattern README into Chinese
> translated the async method invocation pattern into Chinese

- zh/async-method-invocation/README.md
- zh/balking/README.md
- zh/business-delegate/README.md
Pull request title：
- Chinese translation correction
Pull request description：
Revise part of the Chinese translation to make it more expressive
- replace the translation of _'Intent'_ with _'含义'_
- replace the translation of _'Applicability'_ with _'适用场景'_
- replace the translation of _'Credits'_ with _'引用'_
> Chinese translation correction

- zh/circuit-breaker/README.md
- zh/collection-pipeline/README.md
- zh/composite-entity/README.md
- zh/data-bus/README.md
- zh/data-mapper/README.md
- zh/double-checked-locking/README.md
- zh/factory-kit/README.md
- zh/factory/README.md
- zh/sharding/README.md
- Translate some of the README files into Chinese
Includes readme docs for the following design patterns：
> Translate some of the README docs into Chinese

- bridge/src/main/java/com/iluwatar/bridge/Hammer.java
- bridge/src/main/java/com/iluwatar/bridge/Sword.java
Minor changes...grammatical fixes in bridge pattern. No biggie....just trying out GitHub to learn how to use it!
> change 'swinged' to 'swung' in sword.java and hammer.java of bridge pattern

- abstract-factory/README.md
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/App.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfArmy.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfCastle.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfKing.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcArmy.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcCastle.java
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcKing.java
- abstract-factory/src/test/java/com/iluwatar/abstractfactory/AbstractFactoryTest.java
- abstract-factory/src/test/java/com/iluwatar/abstractfactory/AppTest.java
This pull request contains a set of grammatical fixes for the Abstract Factory pattern.
> Grammatical fixes for Abstract Factory

- localization/pt/README.md
portuguese translation and languages codes
translation of the project description into Portuguese, more specifically pt-br(Brazilian Portuguese).
> portuguese translation and languages codes

- README.md
Corrected some sentences by adding hyphens and commas wherever required and changed one sentence to make it grammatically more correct.
> Correcting some grammatical errors of  README.md

- event-aggregator/README.md
- Issue #590 
- Adds explanation for Event Aggregator pattern
> Explanation for event aggregator

- unit-of-work/README.md
- unit-of-work/etc/unit-of-work.ucls
- unit-of-work/src/main/java/com/iluwatar/unitofwork/App.java
- unit-of-work/src/main/java/com/iluwatar/unitofwork/ArmsDealer.java
- unit-of-work/src/main/java/com/iluwatar/unitofwork/Weapon.java
- unit-of-work/src/main/java/com/iluwatar/unitofwork/WeaponDatabase.java
- unit-of-work/src/test/java/com/iluwatar/unitofwork/ArmsDealerTest.java
This pull request contains some improvements to the unit of work pattern.
- Update the topic of the example to be more interesting
- Fix grammar and spelling mistakes
> Refactor unit of work pattern

- factory-kit/README.md
- factory-kit/src/main/java/com/iluwatar/factorykit/App.java
Partial fix for issue #590 (explanation for design patterns)
- Adds an explanation for factory kit pattern
- Improves grammar and spelling
> Add explanation for factory kit

- value-object/README.md
- value-object/src/main/java/com/iluwatar/value/object/App.java
- value-object/src/main/java/com/iluwatar/value/object/HeroStat.java
In this pull request
- Add explanation for value object pattern and fix part of #590 
- Refactor the value object implementation
- Fix grammar and spelling
> Refactor and add explanation for value object

- trampoline/README.md
- trampoline/src/main/java/com/iluwatar/trampoline/Trampoline.java
- trampoline/src/main/java/com/iluwatar/trampoline/TrampolineApp.java
This pull request contains a few simple improvements to the Trampoline pattern
- Fixes grammar and spelling
- Updates the example topic
> Check spelling and update topic in Trampoline pattern

- execute-around/README.md
- execute-around/src/main/java/com/iluwatar/execute/around/App.java
- execute-around/src/main/java/com/iluwatar/execute/around/SimpleFileWriter.java
This pull request updates Execute Around idiom example
- Make the example output the execution steps to console (previously didn't output anything)
- Add comments to the source code
- Update the example topic
- Fix grammar and spelling
> Refactor execute around idiom

- multiton/README.md
- multiton/src/main/java/com/iluwatar/multiton/App.java
- multiton/src/test/java/com/iluwatar/multiton/NazgulTest.java
In this pull request
- Fix grammar and spelling for Multiton pattern
- Update example's console output
> Update Multiton example

- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/Hayes.java
- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/Modem.java
- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/Zoom.java
- Convert the abstract class "Modem" into an interface
- as i changed the modem.java two files are also changed with it 
>  modified modem.java

- acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/Modem.java
- naked-objects/README
**Correction of the CheckStyle issue the project acyclic-visitor**
This pull request correct the checkstyle issue in the project _acyclic-visitor_
Initialy, the pull request was intented to correct the CI error due to the test failure in the project _naked-object_. The issue is related to `JDO Enhancer` that seems to not be executed by the maven plugin in the CI. Locally it works fine.
For now the issue in _acyclic-visitor_ is resolved.
> Correction of the CheckStyle issue the project acyclic-visitor

- execute-around/src/main/java/com/iluwatar/execute/around/App.java
Fix for sonar blocker violation
- Fix for sonar violation
- https://github.com/iluwatar/java-design-patterns/issues/1012
> Surrounded with try with resources

- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/DefaultCircuitBreaker.java
Fix Inssue #1957 about Casting
> Inssue #1957

- combinator/src/main/java/com/iluwatar/combinator/Finder.java
> FIX wrong notes

- combinator/README.md
With the response of the issue #590. I've added the explanation for combinators in its readme.md file. @iluwatar
> Added Explanation for Combinators pattern along with the benefits #590

- cqrs/src/main/java/com/iluwatar/cqrs/queries/QueryServiceImpl.java
Remove deprecated method to ease Hibernate upgrade.
Fix the following deprecated method reported by Sonar in [QueryServiceImpl.java](https://sonarcloud.io/project/issues?fileUuids=AW3G0SevwB6UiZzQNqWr&resolved=false&id=iluwatar_java-design-patterns).
> Remove deprecated method to ease Hibernate upgrade

- localization/vi/README.md
I translate `README.md` file and add it as new file under `/localization/vi/` folder.
> Add localization for Vietnamese

- localization/es/abstract-document/README.md
- localization/es/abstract-factory/README.md
Translates the abstract-factory design pattern's readme file to Spanish. Closes #2066
> Closes #2066 Translate the abstract-factory readme to Spanish

- localization/es/active-object/README.md
Translates the active-object design pattern's readme file to Spanish. Closes #2077
> Closes #2077 Translate the active-object readme to Spanish

- localization/es/acyclic-visitor/README.md
Translates the acyclic-visitor design pattern's readme file to Spanish. Closes #2089
> Closes #2089 Translate the acyclic-visitor readme to Spanish

- .all-contributorsrc
- data-transfer-object/src/main/java/com/iluwatar/datatransfer/App.java
- data-transfer-object/src/main/java/com/iluwatar/datatransfer/product/Product.java
- data-transfer-object/src/main/java/com/iluwatar/datatransfer/product/ProductResource.java
Adding lombok to Product object, this way we can use more modern way to resolve the getters, setters, constructors and builders
Closes https://github.com/iluwatar/java-design-patterns/issues/2096
> Adding lombok to data-transfer-object pattern

- subclass-sandbox/README.md
Updated README for subclass-sandbox design pattern
- Add the explanation part for the README
This PR is regarding issue #590
> Updated README for subclass-sandbox design pattern

- step-builder/src/main/java/com/iluwatar/stepbuilder/Character.java
This PR adds lombok to the step-builder pattern, making the code cleaner and easier to read/maintain
Closes https://github.com/iluwatar/java-design-patterns/issues/2107
> Adding lombok to step-builder pattern

- localization/ko/template-method/README.md
> Closes iluwatar#2082 Translate template-method pattern readme to Korean

- delegation/README.md
added explanation for a delegation pattern
> #590 explanation for a delegation pattern

- .github/workflows/maven-ci.yml
- .github/workflows/maven-pr-builder.yml
Upgrade actions to:
* `actions/checkout@v3`
* `actions/setup-java@v3`
* `actions/cache@v3`
> Bump GitHub Actions

- reader-writer-lock/README.md
In this pull request:
- Fix for issue https://github.com/iluwatar/java-design-patterns/issues/590 (explanation for design patterns)
- Adds an explanation for reader-writer lock to `README.MD`
> Added Explanation for Reader-writer lock #590

- localization/np/README.md
I just change in localization because there is no Nepali language so I just add the Nepali language. It helps Nepali people.
> Add Nepali language localization support for the design patterns

- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/DefaultCircuitBreaker.java
- circuit-breaker/src/test/java/com/iluwatar/circuitbreaker/DefaultCircuitBreakerTest.java
[x] Updated documentation on comments on DefaultCircuitBreaker args,
> Updated documentation on comments on DefaultCircuitBreaker args

- data-bus/README.md
In this pull request, the main and only change is an addition of the explanation for the data-bus design pattern within the README.MD file for issue #590
> Add Explanation for Data-Bus Design Pattern #590 

- localization/ko/proxy/README.md
> Closes iluwatar#2160 Translate proxy pattern readme to Korean

- localization/ko/builder/README.md
> Closes iluwatar#2161 Translate builder pattern readme to Korean

- localization/ko/iterator/README.md
> Closes iluwatar#2162 Translate iterator pattern readme to Korean

- composite-view/src/main/java/com/iluwatar/compositeview/AppServlet.java
CRITICAL Sonar issue fix for duplicate string fixes #1012 
Replaced multiple occurrences of string with constant field.
> CRITICAL Sonar issue fix for duplicate string fixes #1012

- special-case/src/main/java/com/iluwatar/specialcase/App.java
CRITICAL Sonar issue fix for duplicate string fixes #1012 
Replaced multiple occurrences of string with constant field to fix CRITICAL Sonar findings.
> Sonar CRITICAL issue fixes

- producer-consumer/README.md
The explanation for Producer-Consumer Design
In this pull request, I have changed README for the Producer-Consumer design pattern from issue #590
> Adding explanation for Producer-Consumer Design Pattern

- localization/vi/abstract-factory/README.md
I translate `abstract-factory` pattern to Vietnamese.
> Localize abstract-factory pattern to Vietnamese

- localization/vi/active-object/README.md
I translate `active-object` pattern to Vietnamese
> Localize active-object to Vietnamese

- localization/vi/abstract-document/README.md
I translate `abstract-document` pattern to Vietnamese
> Localize abstract-document to Vietnamese

- model-view-controller/README.md
Explanation for MVC design pattern
- Refer to the issue  https://github.com/iluwatar/java-design-patterns/issues/2242
Adds explanation for MVC design pattern
> Adds explanation for MVC design pattern

- model-view-presenter/README.md
Explanation for MVP design pattern
- Refer to the issue #2243 
Adds explanation for MVP design pattern
> Adds explanation for MVP design pattern

- identity-map/README.md
- intercepting-filter/README.md
- interpreter/README.md
- iterator/README.md
> Fix yaml frontmatter of several patterns

- data-mapper/README.md
Pull request description：
- Solve the Issue#2220 [(https://github.com/iluwatar/java-design-patterns/issues/2220]
- Adds an explanation for Data mapper to `README.MD`
> Added README.md explanation in Data mapper

- domain-model/src/main/java/com/iluwatar/domainmodel/App.java
- metadata-mapping/README.md
- metadata-mapping/src/main/java/com/iluwatar/metamapping/utils/DatabaseUtil.java
- metadata-mapping/src/main/resources/com/iluwatar/metamapping/model/User.hbm.xml
- pom.xml
- transaction-script/src/main/java/com/iluwatar/transactionscript/RoomSchemaSql.java
> Fix #2297: Upgrade H2

- localization/pt/builder/README.md
I'll translate the readme file of the builder design pattern to Portuguese and place it under localization.pt.builder.
> Translate the builder readme to Portuguese

- localization/pt/adapter/README.md
translation of adapter pattern to PT-BR
- Translation of README in Adapter pattern to Brazilian portuguese
- Translation to Portuguese #2285
- This pull request add the translation of the adapter pattern to Brazilian portuguese
> translation of adapter pattern to PT-BR

- feature-toggle/src/main/java/com/iluwatar/featuretoggle/user/UserGroup.java
- flyweight/src/main/java/com/iluwatar/flyweight/PotionFactory.java
- flyweight/src/test/java/com/iluwatar/flyweight/AlchemistShopTest.java
I have addressed two minor issues on #2325 : typo and #2326 : small code optimization and refactoring for better readability
> Issues #2326 and #2325

- decorator/README.md
> Corrected quote from Wikipedia for Decorator Pattern article.

- .github/stale.yml
- .github/workflows/maven-ci.yml
- pom.xml
- Set Java language level to 17
- Update stale bot config
- Update CI build
> Set Java language level

- event-sourcing/pom.xml
- pom.xml
- typeobjectpattern/pom.xml
- typeobjectpattern/src/main/java/com/iluwatar/typeobject/App.java
- typeobjectpattern/src/main/java/com/iluwatar/typeobject/CellPool.java
- typeobjectpattern/src/main/java/com/iluwatar/typeobject/JsonParser.java
- typeobjectpattern/src/main/resources/candy.json
Last release of `json-simple` is from 2009. 
Fixes #2037
> dep: replace json-simple with gson

- visitor/README.md
This PR helps for solving #1968 
> docs:Fix documentation errors

- .github/workflows/maven-pr-builder.yml
> Allow secrets in incoming pull requests

- .github/workflows/maven-pr-builder.yml
> Improve PR analysis

- README.md
- localization/it/README.md
Correct some languages and syntax errors inside the IT README file
> Modified IT README file (#2314)

- .github/workflows/maven-pr-builder.yml
- client-session/etc/client-session.urm.puml
- context-object/README.md
- context-object/src/main/java/com/iluwatar/context/object/App.java
- context-object/src/main/java/com/iluwatar/context/object/LayerA.java
- context-object/src/main/java/com/iluwatar/context/object/LayerB.java
- context-object/src/main/java/com/iluwatar/context/object/LayerC.java
- context-object/src/main/java/com/iluwatar/context/object/ServiceContext.java
- context-object/src/main/java/com/iluwatar/context/object/ServiceContextFactory.java
- context-object/src/test/java/com/iluwatar/contect/object/AppTest.java
- context-object/src/test/java/com/iluwatar/contect/object/ServiceContextTest.java
- page-controller/src/main/resources/application.properties
- page-controller/src/main/resources/templates/signup.html
- page-controller/src/main/resources/templates/user.html
- page-controller/src/test/java/com/iluwatar/page/controller/UserControllerTest.java
- page-controller/src/test/java/com/iluwatar/page/controller/UserModelTest.java
- pom.xml
- Include Context Object pattern in the parent pom.xml and fix the build
> Fix context object

- pom.xml
Reverts iluwatar/java-design-patterns#2418
> Revert "build(deps): bump maven-checkstyle-plugin from 3.1.0 to 3.2.0"

- .github/workflows/maven-pr-builder.yml
Reverts iluwatar/java-design-patterns#2424
> Revert "Update PR builder"

- event-driven-architecture/src/main/java/com/iluwatar/eda/event/UserCreatedEvent.java
- event-driven-architecture/src/main/java/com/iluwatar/eda/event/UserUpdatedEvent.java
- event-driven-architecture/src/main/java/com/iluwatar/eda/framework/EventDispatcher.java
- event-driven-architecture/src/main/java/com/iluwatar/eda/framework/Handler.java
- event-driven-architecture/src/test/java/com/iluwatar/eda/AppTest.java
#2428 
I corrected some typos :)
> docs: correct typos in javadoc

- event-sourcing/README.md
- event-sourcing/src/main/java/com/iluwatar/event/sourcing/app/App.java
- event-sourcing/src/main/java/com/iluwatar/event/sourcing/domain/Account.java
- event-sourcing/src/main/java/com/iluwatar/event/sourcing/event/AccountCreateEvent.java
- event-sourcing/src/main/java/com/iluwatar/event/sourcing/event/MoneyDepositEvent.java
- event-sourcing/src/main/java/com/iluwatar/event/sourcing/event/MoneyTransferEvent.java
- event-sourcing/src/main/java/com/iluwatar/event/sourcing/processor/JsonFileJournal.java
- event-sourcing/src/test/java/IntegrationTest.java
> fix: correct typos in event-sourcing

- localization/zh/README.md
Fixed Broken linkage on Chinese localization document.
> Issue #2333 Fixed.

- factory-kit/src/main/java/com/iluwatar/factorykit/App.java
- refactor: use simple forEach.
> refactor: use simple forEach.

- abstract-factory/README.md
- abstract-factory/src/main/java/com/iluwatar/abstractfactory/Kingdom.java
- circuit-breaker/README.md
- circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/DefaultCircuitBreaker.java
- component/src/main/java/com/iluwatar/component/component/inputcomponent/PlayerInputComponent.java
- facade/README.md
- facade/src/main/java/com/iluwatar/facade/DwarvenMineWorker.java
- flyweight/README.md
- flyweight/src/main/java/com/iluwatar/flyweight/PotionFactory.java
- interpreter/src/main/java/com/iluwatar/interpreter/App.java
- leader-election/src/main/java/com/iluwatar/leaderelection/AbstractInstance.java
- localization/es/abstract-factory/README.md
- localization/hi/abstract-factory/README.md
- localization/pt/abstract-factory/README.md
- localization/pt/facade/README.md
- localization/vi/abstract-factory/README.md
- localization/zh/abstract-factory/README.md
- localization/zh/circuit-breaker/README.md
- localization/zh/facade/README.md
- memento/README.md
- memento/src/main/java/com/iluwatar/memento/Star.java
- model-view-intent/src/main/java/com/iluwatar/model/view/intent/CalculatorViewModel.java
- sharding/src/main/java/com/iluwatar/sharding/RangeShardManager.java
Changed all the switch expression according to the JAVA 17.
> issue#2376

- localization/ko/README.md
Fix ko README.md 
Update badge images (invisible image),
Add Links to move another translated languages.
Thank you for your effort.
It is really helpful to study design patterns.
Thank you so much.
> Fix ko(README.md) - update badges, Add Links

- localization/it/README.md
Minor language improvements, including typos and language usage.
> Update Italian README.md

- proxy/README.md
##Added New Known Use on Proxy Design Pattern
- As mentioned on issue #2507 Apple UIKit's UIAppearance use of proxy design pattern was added on README.md file under "Known uses" section. The [link ](https://developer.apple.com/documentation/uikit/uiappearance) that is used is the same that provided by the initiator of the issue.
- No extra changes were applied, since the fix is simple.
> enhancement: added proxy pattern known use (#2507)

- typeobjectpattern/README.md
Fixes #2266 Explanation for Type-Object
Updating Readme.md file of TypeObject pattern.
> Update README.md of typeObjectpattern

- page-object/README.md
Fixes #2250 Explanation for Page Object
Updated the readme.md file accordingly.
> Update README.md for Page object design pattern

- layers/README.md
- localization/es/layers/README.md
Task of #2277
- Translates the Layers Pattern to Spanish
- Minor formatting fix to the original README
> Translates Layers Pattern to Spanish

- localization/es/lazy-loading/README.md
Task of #2277
- Translates the Lazy Loading Pattern to Spanish
> Translates Lazy Loading Pattern to Spanish

- localization/pt/proxy/README.md
Translate Proxy Pattern to portuguese.
- This PR is for issue #2722 
- In this PR I've added the Portuguese translation for proxy.
- made proxy folder in 'localization/pt'
- made 'README.md' for proxy page in Portuguese
> Translate Proxy Pattern to portuguese.

- leader-election/README.md
fix: #2238 
In explanation section, these below topics are added in readme.md file
- Real world example
- Wikipedia says
- Programmatic example: Ring and Bully algorithms
Here the screenshot:
> fix issue ID: #2238 modify Readme.md to add explanation of leader-election

- health-check/README.md
Update README.md for Health Check Pattern (Resolves #2782)
As there is no Wikipedia page for the pattern, if there is a suggestion for the wikipedia says title, I would happy to commit changes.
This Pull Request updates the `README.md` file for the Health Check Pattern, addressing the issue [#2782](https://github.com/iluwatar/java-design-patterns/issues/2782). 
**Key Changes:**
- Added a link to the Health Check API pattern on [Microservices.io](https://microservices.io/patterns/observability/health-check-api.html), providing a comprehensive explanation and insights into the pattern.
- Ensured that the README continues to offer a detailed overview of the pattern, its applicability, known uses, and programmatic examples in a microservices context.
These updates aim to enhance the README by …
> Update README.md for Health Check Pattern

- property/README.md
Update README.md for Property
- Fully explain property design pattern.
- Update https://github.com/iluwatar/java-design-patterns/issues/2254
- Update Readme.md file in property
> Update README.md for Property Design Pattern

- localization/it/observer/README.md
Translation of the 'Observer' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Observer' design pattern, which explains the pattern itself.
- Placed the new README.md file in the 'localization/it/observer' directory.
- Provided the link diagram of the class structure in the Italian README.md, ensuring it aligns with the content of the …
> translation: translation of observer pattern to Italian

- localization/it/iterator/README.md
Translation of the 'Iterator' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Iterator' design pattern, which explains the pattern itself.
This pull request is related to issue https://github.com/iluwatar/java-design-patterns/issues/2314
- Placed the new README.md file in the 'localization/it/iterator' directory.
- Provided the link diagram of the class structure in the Italian …
> translation: translation of iterator pattern to Italian

- proxy/README.md
- Removed 'Apple UIKit's' as it is not mentioned to do.
- #2507 
> issue#2507 Removed 'Apple UIKit's' as it is not mentioned to do.

- single-table-inheritance/pom.xml
- single-table-inheritance/src/main/java/com/iluwatar/entity/Car.java
- single-table-inheritance/src/main/java/com/iluwatar/entity/Freighter.java
- single-table-inheritance/src/main/java/com/iluwatar/entity/Train.java
- single-table-inheritance/src/main/java/com/iluwatar/entity/Truck.java
- single-table-inheritance/src/main/java/com/iluwatar/entity/Vehicle.java
#2825
Change javax library to jakarta
> Updated the imports in code of the single table inheritance pattern for SpringBoot 3.x

- combinator/README.md
- combinator/src/test/java/com/iluwatar/combinator/FinderTest.java
- combinator/src/test/java/com/iluwatar/combinator/FindersTest.java
> Explanation for Combinator

- abstract-document/src/main/java/com/iluwatar/abstractdocument/AbstractDocument.java
- abstract-document/src/test/java/com/iluwatar/abstractdocument/AbstractDocumentTest.java
- adapter/pom.xml
- singleton/src/test/java/com/iluwatar/singleton/BillPughImplementationTest.java
This PR refactors the Abstract Document by making the variable names more clearer to understand  and uses extract method refactoring logic to build a new method called "buildStringRepresentation".
It also adds new test cases for better code coverage.
> Changes to make Abstract-Document and Adapter better.

- data-locality/README.md
- data-locality/src/test/java/com/iluwatar/data/locality/ApplicationTest.java
> Data locality docs

- data-mapper/README.md
- data-mapper/src/main/java/com/iluwatar/datamapper/DataMapperException.java
- data-mapper/src/main/java/com/iluwatar/datamapper/Student.java
- data-mapper/src/main/java/com/iluwatar/datamapper/StudentDataMapperImpl.java
- data-mapper/src/test/java/com/iluwatar/datamapper/AppTest.java
- data-mapper/src/test/java/com/iluwatar/datamapper/StudentTest.java
> Data mapper explanation

- dirty-flag/README.md
- dirty-flag/src/main/java/com/iluwatar/dirtyflag/DataFetcher.java
- dirty-flag/src/main/resources/world.txt
- dirty-flag/src/test/java/org/dirty/flag/AppTest.java
> Dirty Flag explanation

- server-session/README.md
- server-session/pom.xml
- server-session/src/main/java/com/iluwatar/sessionserver/App.java
- server-session/src/main/java/com/iluwatar/sessionserver/LoginHandler.java
- server-session/src/main/java/com/iluwatar/sessionserver/LogoutHandler.java
- server-session/src/test/java/com.iluwatar.sessionserver/LoginHandlerTest.java
- server-session/src/test/java/com.iluwatar.sessionserver/LogoutHandlerTest.java
This pull request solves issue #2848
A basic implementation of the server session pattern
> #2848 Moved project from private project directory to forked repo

- double-dispatch/README.md
- double-dispatch/src/main/java/com/iluwatar/doubledispatch/GameObject.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/AppTest.java
- double-dispatch/src/test/java/com/iluwatar/doubledispatch/RectangleTest.java
> Double dispatch explanation

- event-sourcing/README.md
> Add event sourcing explanation

- resource-acquisition-is-initialization/README.md
#2257 Added Explanation to Resource Acquisition is Initialisation README.md
Added explanations of the following:
- The explanation consists of
- Real world example
- Wikipedia says
- Programmatic example
> #2257 Added Explanation to Resource Acquisition is Initialisation README.md

- subclass-sandbox/src/test/java/com/iluwatar/subclasssandbox/GroundDiveTest.java
- subclass-sandbox/src/test/java/com/iluwatar/subclasssandbox/SkyLaunchTest.java
Fixes Subclass Sandbox tests and re-enables
Close #2860
> Subclass Sandbox tests fixed and re-enabled (#2860)

- flux/README.md
- flux/src/main/java/com/iluwatar/flux/action/ContentAction.java
- flux/src/main/java/com/iluwatar/flux/action/MenuAction.java
- flux/src/main/java/com/iluwatar/flux/app/App.java
- flux/src/main/java/com/iluwatar/flux/dispatcher/Dispatcher.java
- flux/src/main/java/com/iluwatar/flux/store/ContentStore.java
- flux/src/main/java/com/iluwatar/flux/store/MenuStore.java
> Improve docs and add explanation for flux

- front-controller/README.md
- front-controller/src/main/java/com/iluwatar/front/controller/App.java
- front-controller/src/main/java/com/iluwatar/front/controller/ApplicationException.java
> Add explanation for front controller

- hexagonal/README.md
- hexagonal/src/main/java/com/iluwatar/hexagonal/administration/ConsoleAdministrationSrvImpl.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/banking/MongoBank.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/database/MongoTicketRepository.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryAdministration.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryService.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryTicket.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryUtils.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/domain/PlayerDetails.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/eventlog/MongoEventLog.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/eventlog/StdOutEventLog.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/mongo/MongoConnectionPropertiesLoader.java
- hexagonal/src/main/java/com/iluwatar/hexagonal/sampledata/SampleData.java
- hexagonal/src/test/java/com/iluwatar/hexagonal/database/MongoTicketRepositoryTest.java
> Add explanation for hexagonal architecture

- lazy-loading/README.md
- lazy-loading/src/test/java/com/iluwatar/lazy/loading/AbstractHolderTest.java
- lazy-loading/src/test/java/com/iluwatar/lazy/loading/HolderNaiveTest.java
- lazy-loading/src/test/java/com/iluwatar/lazy/loading/HolderThreadSafeTest.java
- lazy-loading/src/test/java/com/iluwatar/lazy/loading/Java8HolderTest.java
> Lazy loading explanation

- marker/README.md
- marker/src/main/java/App.java
> Add explanation for marker

- game-loop/README.md
Close #2950 
This PR adds documentation for other two game loop implementations
> issue:#2950 added_documentation_for_game_loop_implementations

- partial-response/README.md
- partial-response/src/main/java/com/iluwatar/partialresponse/Video.java
> Explanation for partial response

- page-controller/README.md
- reactor/README.md
- reactor/src/main/java/com/iluwatar/reactor/app/LoggingHandler.java
- reactor/src/main/java/com/iluwatar/reactor/framework/AbstractNioChannel.java
- reactor/src/main/java/com/iluwatar/reactor/framework/NioDatagramChannel.java
> Explanation for reactor

- retry/README.md
- role-object/README.md
- role-object/src/main/java/com/iluwatar/roleobject/BorrowerRole.java
- role-object/src/main/java/com/iluwatar/roleobject/InvestorRole.java
> Update role object docs

- cqrs/README.md
- saga/README.md
- saga/src/main/java/com/iluwatar/saga/choreography/Saga.java
- saga/src/main/java/com/iluwatar/saga/choreography/WithdrawMoneyService.java
- saga/src/main/java/com/iluwatar/saga/orchestration/ChapterResult.java
- saga/src/main/java/com/iluwatar/saga/orchestration/Saga.java
- saga/src/main/java/com/iluwatar/saga/orchestration/WithdrawMoneyService.java
> Saga explanation

- service-locator/README.md
- service-locator/src/main/java/com/iluwatar/servicelocator/InitContext.java
- service-locator/src/main/java/com/iluwatar/servicelocator/Service.java
- service-locator/src/main/java/com/iluwatar/servicelocator/ServiceLocator.java
> Update service locator docs

- flyweight/README.md
> #2546 - Remove code repetition from flyweight README

- step-builder/README.md
- strangler/README.md
- strangler/src/main/java/com/iluwatar/strangler/HalfArithmetic.java
- strangler/src/main/java/com/iluwatar/strangler/NewArithmetic.java
> Strangler explanation

- pom.xml
- Upgraded Guice dependency from the previous version to 6.0.0 in the project's build configuration.
- Ensured all existing tests pass without any modifications.
- Verified that the project builds successfully and runs as expected with the new version of Guice.
Close #2974
> Upgraded Guice dependency to 6.0.0

- serialized-lob/pom.xml
> Use the latest h2 version in serialized lob

- localization/fr/business-delegate/README.md
Translation of the Business-delegate pattern in french. 
Issue : Translate to French #2278
> Translation of business-delegate pattern in french.

- composite-view/web/header.jsp
i done this as an assignment of Tublian OS internship
> Added Home button to header for easy navigation to home page 

- abstract-document/src/test/java/com/iluwatar/abstractdocument/AbstractDocumentTest.java
Added to AbstractDocumentTest verification of originalValue in document before updating document with updateValue
> Added to AbstractDocumentTest verification of originalValue in document

- hexagonal-architecture/README.md
- sharding/src/main/java/com/iluwatar/sharding/Data.java
> chore: fix some typos in comment

- localization/es/map-reduce/README.md
This pull request translates the README.md file of the MapReduce design pattern in Java. The translation includes all types of technical terms as well as the links to the various resources given in the original README.md file.
Changes apply to **Issue #2277** (Translate to Spanish); already existent issue regarding the Spanish translation of the whole repository.
All the best,
Francisco!
> Added and translated map-reduce README.md to Spanish.

- pom.xml
Removes duplicated dependency in pom.xml
> chore: removed duplicated dependency
