README.md, callback/src/main/java/com/iluwatar/App.java
Guess this description will be more close to accurate.
Also come up with kind of controversial **Real world example**: one of [CyclicBarrier] (http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CyclicBarrier.html#CyclicBarrier%28int,%20java.lang.Runnable%29) constructors can accept callback that will be triggered every time when barrier is tripped.
Though ideologically, I think, it is good Callback example its very differ in implementation.
Would it be appropriate to mention this case in description?
=> Callback pattern description amendment

README.md
The FAQ section about the difference between double dispatch and Visitor states that C++ and Java **support** this. But actually they do not support it. Have corrected the mistake.
=> Changed improper description about double dispatch in FAQ section

flyweight/index.md, interpreter/index.md, model-view-presenter/index.md
See on http://iluwatar.github.io/java-design-patterns/patterns/flyweight/ that `*` are not converted to proper unordered lists.
=> Jekyll does not like enumerations w/o blank lines

observer/src/main/java/com/iluwatar/observer/App.java, observer/src/main/java/com/iluwatar/observer/Hobbits.java, observer/src/main/java/com/iluwatar/observer/Orcs.java, observer/src/main/java/com/iluwatar/observer/Weather.java, observer/src/main/java/com/iluwatar/observer/WeatherObserver.java, observer/src/main/java/com/iluwatar/observer/WeatherType.java, observer/src/main/java/com/iluwatar/observer/generic/GHobbits.java, observer/src/main/java/com/iluwatar/observer/generic/GOrcs.java, observer/src/main/java/com/iluwatar/observer/generic/GWeather.java, observer/src/main/java/com/iluwatar/observer/generic/Observable.java, observer/src/main/java/com/iluwatar/observer/generic/Observer.java, observer/src/test/java/com/iluwatar/observer/AppTest.java
If everything looks good in this PR, I can go ahead & make changes to others.
=> Reformat Code According to Google Style Guide #224

async-method-invocation/pom.xml, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutorTest.java
Add proper unit tests for async-method-invocation. This should allow you to tick off the async-method-invocation item on the 'to-junit-test' list in issue #293
=> Add proper unit tests for async-method-invocation #293

front-controller/src/main/java/com/iluwatar/front/controller/FrontController.java
Hiya!
I was just checking out this pattern and it returned three times the same string 
> Error 500
> Error 500
> Error 500
Correct output should be
>Displaying archers
>Displaying catapults
>Error 500
The problem was the name of the package was not the correct one in FrontController.java, line 28.
The class should be probably be uptaded to not get the Class names from hard-coded Strings.
=> Just  Just a quick fix for the Front-controller pattern.

mediator/src/main/java/com/iluwatar/mediator/PartyImpl.java, model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileSelectorJFrame.java, naked-objects/fixture/src/main/java/domainapp/fixture/modules/simple/SimpleObjectCreate.java, naked-objects/fixture/src/main/java/domainapp/fixture/scenarios/RecreateSimpleObjects.java, poison-pill/src/main/java/com/iluwatar/poison/pill/Consumer.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1698 - Objects should be compared with equals() and squid:HiddenFieldCheck - Local variables should not shadow class fields
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1698
Kirill Vlasov
=> Code quality fixes

caching/src/main/java/com/iluwatar/caching/AppManager.java, caching/src/main/java/com/iluwatar/caching/CacheStore.java, caching/src/main/java/com/iluwatar/caching/DbManager.java, naked-objects/integtests/src/test/java/domainapp/integtests/bootstrap/SimpleAppSystemInitializer.java, service-layer/src/main/java/com/iluwatar/servicelayer/hibernate/HibernateUtil.java, service-locator/src/main/java/com/iluwatar/servicelocator/ServiceLocator.java, tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishSerializer.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
Kirill Vlasov
=> Utility classes should not have public constructors

callback/src/main/java/com/iluwatar/callback/LambdasApp.java, callback/src/test/java/com/iluwatar/callback/AppTest.java
Created a Lambdas example for the callback pattern, using the same output of the traditional version. Have also added another unit test for issue #334
=> Provide a simple example for Callback Pattern using Lambdas

caching/src/main/java/com/iluwatar/caching/DbManager.java, caching/src/main/java/com/iluwatar/caching/LruCache.java, composite/src/main/java/com/iluwatar/composite/LetterComposite.java, composite/src/main/java/com/iluwatar/composite/Messenger.java, dao/src/main/java/com/iluwatar/dao/App.java, dao/src/test/java/com/iluwatar/dao/CustomerDaoImplTest.java, layers/src/main/java/com/iluwatar/layers/CakeBakingServiceImpl.java, poison-pill/src/main/java/com/iluwatar/poison/pill/SimpleMessageQueue.java, producer-consumer/src/main/java/com/iluwatar/producer/consumer/ItemQueue.java, service-layer/src/main/java/com/iluwatar/servicelayer/magic/MagicServiceImpl.java, service-layer/src/main/java/com/iluwatar/servicelayer/spellbook/Spellbook.java, service-layer/src/main/java/com/iluwatar/servicelayer/wizard/Wizard.java, service-locator/src/main/java/com/iluwatar/servicelocator/ServiceCache.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2293 - The diamond operator ("<>") should be used
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2293
M-Ezzat
=> squid:S2293 - The diamond operator should be used

builder/src/main/java/com/iluwatar/builder/Hero.java, property/src/main/java/com/iluwatar/property/Character.java, step-builder/src/main/java/com/iluwatar/stepbuilder/Character.java
This pull request is focused on resolving occurrences of Sonar rule pmd:AppendCharacterWithChar - Append Character With Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:AppendCharacterWithChar
M-Ezzat
=> pmd:AppendCharacterWithChar - Append Character With Char

LICENSE.md
[How to use GNU licenses for your own software (Most parts also apply to the MIT license)](http://www.gnu.org/licenses/gpl-howto.html)
> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each release; for example, “Copyright 1998, 1999 Terry Jones” if some versions were finished in 1998 and some were finished in 1999.
> ...
> For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your …
=> Update license year from 2014 to range '2014-2016'

null-object/src/main/java/com/iluwatar/nullobject/NullNode.java, visitor/src/main/java/com/iluwatar/visitor/CommanderVisitor.java, visitor/src/main/java/com/iluwatar/visitor/SergeantVisitor.java, visitor/src/main/java/com/iluwatar/visitor/SoldierVisitor.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1186 - Methods should not 
be empty
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1186
M-Ezzat
=> squid:S1186 - Methods should not be empty

builder/src/main/java/com/iluwatar/builder/Hero.java, caching/src/main/java/com/iluwatar/caching/AppManager.java, caching/src/main/java/com/iluwatar/caching/DbManager.java, flux/src/main/java/com/iluwatar/flux/dispatcher/Dispatcher.java, multiton/src/main/java/com/iluwatar/multiton/Nazgul.java, naked-objects/integtests/src/test/java/domainapp/integtests/bootstrap/SimpleAppSystemInitializer.java, null-object/src/main/java/com/iluwatar/nullobject/NullNode.java, service-layer/src/main/java/com/iluwatar/servicelayer/hibernate/HibernateUtil.java, service-locator/src/main/java/com/iluwatar/servicelocator/ServiceLocator.java, singleton/src/main/java/com/iluwatar/singleton/InitializingOnDemandHolderIdiom.java, singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java, singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java, step-builder/src/main/java/com/iluwatar/stepbuilder/CharacterStepBuilder.java, tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishSerializer.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2974 - Classes without "public" constructors should be "final"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2974
M-Ezzat
=> squid:S2974 - Classes without public constructors should be final

event-aggregator/src/main/java/com/iluwatar/event/aggregator/EventEmitter.java, iterator/src/main/java/com/iluwatar/iterator/Item.java, layers/src/main/java/com/iluwatar/layers/Cake.java, layers/src/main/java/com/iluwatar/layers/CakeLayer.java, layers/src/main/java/com/iluwatar/layers/CakeTopping.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1699 - Constructors should only call non-overridable methods
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1699
M-Ezzat
=> squid:S1699 - Constructors should only call non-overridable methods

decorator/src/main/java/com/iluwatar/decorator/Troll.java
=> Override annotation added

builder/etc/builder.ucls, builder/src/main/java/com/iluwatar/builder/App.java, builder/src/main/java/com/iluwatar/builder/Hero.java, builder/src/test/java/com/iluwatar/builder/HeroTest.java
To make the builder more readable and meaningful, HeroBuilder should have been renamed to Builder, as mentioned in the comments as well. So I did that. I would appreciate it if somebody would review it. Thanks!
=> Renamed HeroBuilder to Builder

hexagonal/src/main/java/com/iluwatar/hexagonal/administration/ConsoleAdministration.java, hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryService.java, hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryTicketCheckResult.java, hexagonal/src/main/java/com/iluwatar/hexagonal/eventlog/MongoEventLog.java, hexagonal/src/main/java/com/iluwatar/hexagonal/service/ConsoleLottery.java
Sonar bug fixes using Yoda condition in equals expression when comparing String literal with String object. 
Using try-with-resources if we use Scanner to close the underlying stream is a good practice to handle resources.
Minimal refactor.
=> Sonar quality bugfix and minor refactor

dependency-injection/src/main/java/com/iluwatar/dependency/injection/AdvancedSorceress.java, dependency-injection/src/main/java/com/iluwatar/dependency/injection/App.java, dependency-injection/src/test/java/com/iluwatar/dependency/injection/AdvancedSorceressTest.java
There are two types of dependency injection: Constructor dependency injection and Setter Dependency Injection. Both types have pluses and minuses and wide used (f.e. in Spring Framework). This patch describes second type of DI - Setter Dependency Injection. 
Class AdvancedSorceress is constructed by analogy with AdvancedWizard. Difference between them is in the way of dependency injection. Tests attached.
=> Adding Setter Dependency Injection as a second subtype of DI

interpreter/src/test/java/com/iluwatar/interpreter/ExpressionTest.java
Hello,
I am a graduate student at Oregon State University and as a part of my research and subject CS562 Applied Software Engineering project (Study and Refactoring of Functional Interface in Java), I have done refactoring of the functional interface namely:
> BiFunction<Integer,Integer,Integer> --> IntBinaryOperator
My project and research deals with the boxing and unboxing of Wrapper Class and the primitive data-types. I want to know that whether the open source community is ready to accept these micro-optimizing refactoring or not.
Thank you,
Harsh Thakor
=> Refactored the Functional Interface to the Specialized Primitive Functional Interface 

thread-pool/src/test/java/com/iluwatar/threadpool/TaskTest.java
This is another similar change that found. This will greatly improve the performance as the `for `loop runs `128*1024 times` and boxing happens in every loop.
=> Refactored Function<Integer,T> to IntFunction<T>

model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileLoader.java, model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileSelectorPresenter.java, model-view-presenter/src/main/java/com/iluwatar/model/view/presenter/FileSelectorView.java
Marking FileLoader (Model) as Serializable, because model is an interface to provide data and it can provide caching behaviour. Presenter should be able to restore the model in any event.
Marking FileSelectorView as Serializable as I think view is made up of some static structure and Serializable data (from model).
Presenter is an middle-man who manages View and Model. Both View and Model will be given to Presenter by the application. It will not make any harm to make presenter as Serializable. It will be useful serialize model and view as it is tied to one another.
Or, we could set //NOSONAR and let the consumer application framework to decide whether to mark as Serializable or not based on their design.
References: 
https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93presenter …
=> #587 SonarQube reports bugs

dao/src/main/java/com/iluwatar/dao/DbCustomerDao.java
As getAll method returns a Stream, we cannot close the involved resources (connection, statement and resultset) until the stream is closed by the consumer. So try-with-resources is not an option as per sonarqube’s recommendation. But it is still recommended to close statement and result set. When connection pool used, connection is not closed when close() called. It is just returned to the pool.
Using //NOSONAR to avoid false blocker issue.
=> Issue 587 SonarQube reports bugs - Module DAO

async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutor.java
As recommended in
https://sonarcloud.io/organizations/default/rules#rule_key=squid%3AS2274 
Used while insteadof if - for waiting upon a condition.
=> #587 SonarQube reports bugs - async-method-invocation

reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/App.java, reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/Reader.java, reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/ReaderWriterLock.java, reader-writer-lock/src/main/java/com/iluwatar/reader/writer/lock/Writer.java, reader-writer-lock/src/test/java/com/iluwatar/reader/writer/lock/utils/InMemoryAppender.java
Keeping wait() calls with in synchronized block closely to adhere
SonarQube rules.
Avoid nested synchronized block by extracting method.
Added writing and reading time to simulate testing to ensure 
1) writers are waiting for globalMutex to be empty 
2) readers to confirm there is no writers.
=> #587 SonarQube reports bugs reader-writer-lock and refactor

naked-objects/dom/pom.xml, pom.xml
=> Configuration changes needed to run tests on Java 9

naked-objects/README.md
The commit fixes the URL, changing from a non-working URL to an actually
working one.
The URL was copied from the wikipedia page for Naked Objects.
=> Fix naked objects thesis url

factory-method/src/test/java/com/iluwatar/factory/method/FactoryMethodTest.java, prototype/src/test/java/com/iluwatar/prototype/PrototypeTest.java
- The test message for the WeaponType assertion should tell the expected WeaponType instead of the Weapon class name.
- Remove compiler warning of unused generic type in PrototypeTest
=> Fix FactoryMethodTest and PrototypeTest

search_index.json
Some of the patterns contain braces that will break jQuery's
`getJSON` method when it attempts to parse the response. Adding
the `url_encode` filter ensures that this doesn't happen again.
=> #653: Url encode content to fix JSON breaking pattern descriptions

facade/README.md
Fix a small typo in the README page of "Facade" pattern
=> Fix a typo in the "Facade" pattern

abstract-factory/README.md, abstract-factory/src/main/java/com/iluwatar/abstractfactory/App.java, abstract-factory/src/test/java/com/iluwatar/abstractfactory/AbstractFactoryTest.java
The explanation for the pattern mentions that it is "a factory of factories", but the example does not have any factory class that returns the concrete classes of **KingdomFactory**.
This commit removes the direct instantiation of **ElfKingdomFactory** and **OrcKingdomFactory** from **App.main()** and delegates their creation to a new (factory of factories) **FactoryMaker** inner class of **App**.
Even though the pattern itself does not necessarily need this, it helps to synchronize the explanation text with the coding example, making it easier to understand that statement.
=> (Abstract Factory) Add factory of factories

cqrs/src/main/java/com/iluwatar/cqrs/domain/model/Author.java, cqrs/src/main/java/com/iluwatar/cqrs/domain/model/Book.java, cqrs/src/main/java/com/iluwatar/cqrs/dto/Author.java, cqrs/src/main/java/com/iluwatar/cqrs/dto/Book.java, event-aggregator/src/main/java/com/iluwatar/event/aggregator/KingsHand.java, event-aggregator/src/main/java/com/iluwatar/event/aggregator/LordBaelish.java, event-aggregator/src/main/java/com/iluwatar/event/aggregator/LordVarys.java, event-aggregator/src/main/java/com/iluwatar/event/aggregator/Scout.java
This PR removes few more explicit calls to `super()`.
Relates to #694
=> Remove redundant explicit super() constructor calls #694

prototype/src/main/java/com/iluwatar/prototype/App.java, prototype/src/main/java/com/iluwatar/prototype/Beast.java, prototype/src/main/java/com/iluwatar/prototype/ElfBeast.java, prototype/src/main/java/com/iluwatar/prototype/ElfMage.java, prototype/src/main/java/com/iluwatar/prototype/ElfWarlord.java, prototype/src/main/java/com/iluwatar/prototype/HeroFactoryImpl.java, prototype/src/main/java/com/iluwatar/prototype/Mage.java, prototype/src/main/java/com/iluwatar/prototype/OrcBeast.java, prototype/src/main/java/com/iluwatar/prototype/OrcMage.java, prototype/src/main/java/com/iluwatar/prototype/OrcWarlord.java, prototype/src/main/java/com/iluwatar/prototype/Prototype.java, prototype/src/main/java/com/iluwatar/prototype/Warlord.java, prototype/src/test/java/com/iluwatar/prototype/HeroFactoryImplTest.java, prototype/src/test/java/com/iluwatar/prototype/PrototypeTest.java
As per http://www.artima.com/intv/bloch13.html, clone method in java is
broken or confusing. So staying away from clone method.
SonarQube reports code smells #508
- SonarQube recommends Remove this "clone" implementation; use a copy constructor or copy factory instead
- introduced copy method which uses copy constructor. keeps the implementation transparent and expect developer to make deep copy during copy operation.
=> issue 508 - using copy constructor to implement prototype.

pom.xml, trampoline/.gitignore, trampoline/README.md, trampoline/pom.xml, trampoline/src/main/java/com/iluwatar/trampoline/App.java, trampoline/src/main/java/com/iluwatar/trampoline/Trampoline.java, trampoline/src/main/java/com/iluwatar/trampoline/TrampolineApp.java, trampoline/src/test/java/com/iluwatar/trampoline/TrampolineAppTest.java
- Add pattern trampoline.
- #677 -> https://github.com/iluwatar/java-design-patterns/issues/677
- Add readme, code,test.
=> #677 add pattern Trampoline.

interpreter/src/test/java/com/iluwatar/interpreter/ExpressionTest.java, interpreter/src/test/java/com/iluwatar/interpreter/MinusExpressionTest.java, interpreter/src/test/java/com/iluwatar/interpreter/MultiplyExpressionTest.java, interpreter/src/test/java/com/iluwatar/interpreter/NumberExpressionTest.java, interpreter/src/test/java/com/iluwatar/interpreter/PlusExpressionTest.java, observer/src/test/java/com/iluwatar/observer/HobbitsTest.java, observer/src/test/java/com/iluwatar/observer/OrcsTest.java, observer/src/test/java/com/iluwatar/observer/WeatherObserverTest.java, observer/src/test/java/com/iluwatar/observer/generic/GHobbitsTest.java, observer/src/test/java/com/iluwatar/observer/generic/ObserverTest.java, observer/src/test/java/com/iluwatar/observer/generic/OrcsTest.java
Use the TestInstance annotation in class to avoid ```static``` and  enable inhertied of methods refered by MethodSource.
=> Use the @TestInstance annotation

CODE_COVERAGE.md
The command in file `CODE_COVERAGE.md` creates `jacoco.exec` files but not the reports.
This pull request changes the command to generate the reports, making the rest of the file correct.
=> Correct the command for computing code coverage

converter/src/main/java/com/iluwatar/converter/Converter.java
Parameters in Converter class methods was renamed. 
A base class must not contain the concrete entities names or concrete class names
=> Parameters in Converter class methods was renamed. 

throttling/src/test/java/com/iluwatar/throttling/B2BServiceTest.java
I took a look at the Travis logs and the troublesome test. From examining the code and tinkering around, my best guess is that in the Travis environment, the threat that resets the API access limit may prematurely reset the count, making the assertion fail.
I have instead changed the throttler to be an empty implementation (to avoid any unintended resets, which is not the point of the test). Additionally, I changed it to an assertEquals so that in the event of another failure, we can see exactly what the counter ended up being, which will help with debugging.
=> #643 Fix flaky tests for throttling pattern

execute-around/src/main/java/com/iluwatar/execute/around/App.java, execute-around/src/main/java/com/iluwatar/execute/around/FileWriterAction.java
Refactor the Execute Around pattern to use a lambda. Lambdas make such patterns feel lighter weight.
I first heard about this pattern in a talk by Venkat Subramanian. The thrust of the talk was that lambdas made such patterns nicer.
I extracted the lambda to its own variable to make clearer the type it's implementing.
=> Execute Around - use lambda

hexagonal/src/main/java/com/iluwatar/hexagonal/database/MongoTicketRepository.java, hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryNumbers.java, hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryTicketId.java, hexagonal/src/test/java/com/iluwatar/hexagonal/AppTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/banking/InMemoryBankTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/banking/MongoBankTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/database/InMemoryTicketRepositoryTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/database/MongoTicketRepositoryTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryNumbersTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTicketCheckResultTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTicketIdTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTicketTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/PlayerDetailsTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/eventlog/MongoEventLogTest.java
- Refactored LotteryNumbers to use Joiner from guava library to join lottery numbers. 
- Solved potential thread safety issue in LotteryTicketId class, where it was using raw primitive value and incrementing it which is not thread-safe. So used AtomicInteger for brevity 
- assertEquals arguments were in incorrect order at many places, so changed order of those
- Replaced assertFalse and assertTrue at some places with assertEquals and assertNotEquals for reducing complexity of code
-  Removed public modifiers from test cases, as they are no more needed by JUnit 5
=> Minor refactorings in Hexagonal architecture

hexagonal/src/main/java/com/iluwatar/hexagonal/App.java, hexagonal/src/main/java/com/iluwatar/hexagonal/banking/InMemoryBank.java, hexagonal/src/main/java/com/iluwatar/hexagonal/banking/MongoBank.java, hexagonal/src/main/java/com/iluwatar/hexagonal/database/MongoTicketRepository.java, hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryConstants.java, hexagonal/src/main/java/com/iluwatar/hexagonal/domain/LotteryNumbers.java, hexagonal/src/main/java/com/iluwatar/hexagonal/sampledata/SampleData.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryNumbersTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTest.java, hexagonal/src/test/java/com/iluwatar/hexagonal/domain/LotteryTicketTest.java
Fixed wrong 'else if' (it had the same condition as previous 'if' but it should have been just 'else')
Fixed typo and changed Finnish 'saldo' word to 'balance' 
Deleted unused imports
Simplified few other things
=> Hexagonal pattern fixes

abstract-factory/etc/presentation.html, command/etc/presentation.html, factory-method/etc/presentation.html
Sometimes the presentations would fail due to the content of remark.js being delivered through unauthenticated source.
The new source seems to work successfully.
=> Fix script blocking of presentations due to address used to download remark.js

pom.xml, typeobjectpattern/README.md, typeobjectpattern/pom.xml, typeobjectpattern/src/main/java/com/iluwatar/typeobject/App.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/Candy.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/CandyGame.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/Cell.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/CellPool.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/JsonParser.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/candy.json, typeobjectpattern/src/test/java/com/iluwatar/typeobject/CandyGameTest.java, typeobjectpattern/src/test/java/com/iluwatar/typeobject/CellPoolTest.java, typeobjectpattern/src/test/java/com/iluwatar/typeobject/CellTest.java
Type object pattern implementation
=> Type object pattern #555

.travis.yml
Change Travis CI Build Environment to Trusty
- This PR is to fix an issue causing the Travis CI build to fail.  The problem seems to have stemmed from the build using Travis CI's Xenial build environment, which would not allow you to install anything less than java 9.
- This is in reference to Issue #903. 
- The only change made here is one line of code telling Travis CI to use the Trusty build environment instead of the Xenial one.
=> Change Travis CI build env. to Trusty

abstract-document/src/main/java/com/iluwatar/abstractdocument/App.java, abstract-document/src/main/java/com/iluwatar/abstractdocument/domain/HasModel.java, abstract-document/src/main/java/com/iluwatar/abstractdocument/domain/HasParts.java, abstract-document/src/main/java/com/iluwatar/abstractdocument/domain/HasPrice.java, abstract-document/src/main/java/com/iluwatar/abstractdocument/domain/HasType.java, abstract-document/src/main/java/com/iluwatar/abstractdocument/domain/enums/PROPERTY.java, abstract-document/src/main/java/com/iluwatar/abstractdocument/domain/enums/Property.java, abstract-document/src/test/java/com/iluwatar/abstractdocument/DomainTest.java, caching/src/main/java/com/iluwatar/caching/DbManager.java, caching/src/main/java/com/iluwatar/caching/constants/CachingConstants.java, cqrs/src/main/java/com/iluwatar/cqrs/app/App.java, cqrs/src/main/java/com/iluwatar/cqrs/constants/AppConstants.java, cqrs/src/main/java/com/iluwatar/cqrs/queries/QueryServiceImpl.java, dao/src/main/java/com/iluwatar/dao/App.java, data-mapper/src/main/java/com/iluwatar/datamapper/App.java, double-dispatch/src/main/java/com/iluwatar/doubledispatch/Meteoroid.java, double-dispatch/src/main/java/com/iluwatar/doubledispatch/SpaceStationMir.java, double-dispatch/src/main/java/com/iluwatar/doubledispatch/constants/AppConstants.java
- Sonar Queb Issue :  Move constants to a class or enum.
- https://github.com/iluwatar/java-design-patterns/issues/508
- Fixes Sonar Qube Critical Issue : Move constants to a class or enum.
=> 508 : sonar qube critical issue fixes

event-asynchronous/src/main/java/com/iluwatar/event/asynchronous/App.java, event-asynchronous/src/main/java/com/iluwatar/event/asynchronous/EventManager.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/domain/Account.java
Refactor this method to reduce its Cognitive Complexity from 30 to the 15 allowed.
- Sonar Qube COmplexity Issue Fixes
- https://github.com/iluwatar/java-design-patterns/issues/508
-  Cognitive Compexity of Methods has been reduced in these commits
=> 508 : Sonar qube critical Issue Fix

twin/src/test/java/com/iluwatar/twin/BallThreadTest.java
Bug fix for (#860  )
- fixed the failing tests for twin pattern
- removed the timeout from VerificationMode passed to mockito verify method. This timeout was cause for failure. It seemed redundant as well, as there is a timeout on the test itself. 
- Also, the tests were failing because the ballThread.start wasn't getting started fast enough and the Mockito verify gets called before the thread initialization.
=> fixed failing tests (#860)

.travis.yml
- This PR makes Travis CI use Java 8, which requires the Trusty build environment. 
- Refer to the issue #912 
This comes from a known issue with the S3_website repo, which is not actively maintained. It seems to not support anything higher than Java 8, which makes the gh-pages build fail when Travis CI tries to use Java 11.
=> Change Travis CI to use Java 8 for S3_website 

abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfKingdomFactory.java, abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcKingdomFactory.java, acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/ConfigureForDosVisitor.java, acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/ConfigureForUnixVisitor.java, factory-method/src/main/java/com/iluwatar/factory/method/ElfBlacksmith.java, factory-method/src/main/java/com/iluwatar/factory/method/OrcBlacksmith.java, throttling/src/main/java/com/iluwatar/throttling/timer/ThrottleTimerImpl.java
added @override annotation when overriding a method, it helps prevent errors.
=> fix must override a superclass method

singleton/pom.xml, singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java, singleton/src/test/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLockingTest.java
This PR solves issue #761 
- Add a flag to record whether the constructor is invoked for the first time. If not, throw corresponding exception.
- Add test case to test creating new instance by reflection.
=> Fix issue #761

abstract-factory/README.md
=> added new information

aggregator-microservices/aggregator-service/pom.xml, aggregator-microservices/information-microservice/pom.xml, aggregator-microservices/inventory-microservice/pom.xml, api-gateway/api-gateway-service/pom.xml, api-gateway/image-microservice/pom.xml, api-gateway/price-microservice/pom.xml, pom.xml
Dependecy management should be setup in parent POM. Hence not needed in children projects. 
- Fix #834 
- Remove dependecy management for spring-boot in several children projects, redundant.
- Removed version of spring-maven-plugin, redundant, version fetched from parent POM.
=> #834 Fix dependency management issue for POM files

naked-objects/pom.xml, pom.xml
This fixes following issues during build process, #944.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.iluwatar:image-microservice:jar:1.22.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ com.iluwatar:image-microservice:[unknown-version], /home/travis/build/iluwatar/java-design-patterns/api-gateway/image-microservice/pom.xml, line 55, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.iluwatar:price-microservice:jar:1.22.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ com.iluwatar:price-microservice:[unknown-version], …
=> Fix compiler/build warning

pom.xml, repository/pom.xml
Issue:
JAXB API and javax.Annotations were removed from jdk11, so some tests were failing. 
Changes:
Add javax.annotation and java.xml.bind as external maven dependencies
Verification:
Verified tests with jdk-11
=> Fix for issue #954 : Add external Dependencies to run with Java11

eip-aggregator/src/test/java/com/iluwatar/eip/aggregator/routes/AggregatorRouteTest.java, eip-splitter/src/test/java/com/iluwatar/eip/splitter/routes/SplitterRouteTest.java, eip-wire-tap/src/test/java/com/iluwatar/eip/wiretap/routes/WireTapRouteTest.java, layers/pom.xml, layers/src/main/java/com/iluwatar/layers/CakeBakingServiceImpl.java, layers/src/main/resources/applicationContext.xml, pom.xml, repository/pom.xml, repository/src/main/java/com/iluwatar/repository/App.java, repository/src/main/java/com/iluwatar/repository/AppConfig.java, repository/src/main/resources/applicationContext.xml, repository/src/test/java/com/iluwatar/repository/AnnotationBasedRepositoryTest.java, repository/src/test/java/com/iluwatar/repository/AppConfigTest.java, repository/src/test/java/com/iluwatar/repository/RepositoryTest.java
Upgrade camel and spring-data to resolve the security vulnerabilities issue reported by Github.
=> Fix: Github reports security vulnerabilities  #933

cqrs/pom.xml, eip-aggregator/pom.xml, eip-splitter/pom.xml, eip-wire-tap/pom.xml, naked-objects/dom/exclude-pmd.properties, naked-objects/dom/pom.xml, naked-objects/integtests/pom.xml, pom.xml, service-layer/pom.xml, trampoline/pom.xml
Added maven profiles activated by jdk 11, wich will not break java 8 support.
Bumped lombok and datanucleus enhancer as the old versions dont work with 11.
=> Maven profiles to support jdk 11 builds. #948

.travis.yml, cqrs/pom.xml, eip-aggregator/pom.xml, eip-splitter/pom.xml, eip-wire-tap/pom.xml, naked-objects/dom/pom.xml, naked-objects/integtests/pom.xml, pom.xml, service-layer/pom.xml
* Moved java XML and annotations dependencies to project level instead
of as profiles
* Set compiler language level to 11
* Removed jdk8 from travis build
* Kept java level 8 in naked-objects/dom for datanucleus enhancer, for
now.
=> Bump java language to 11 #976 

.travis.yml
SonarCloud analysis does not work from pull requests originated from forks. This PR solves it by disabling SonarCloud analysis for pull requests.
=> #996 disable sonar analysis for pull requests

aggregator-microservices/aggregator-service/pom.xml, aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInformationClientImpl.java, aggregator-microservices/aggregator-service/src/main/java/com/iluwatar/aggregator/microservices/ProductInventoryClientImpl.java, api-gateway/api-gateway-service/pom.xml, api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/ImageClientImpl.java, api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/PriceClientImpl.java, pom.xml
Replaced all of the Apache HttpClients with Java's java.net.http
This is to address ticket #988. As of Java 11 the HTTP Client provides mechanism to perform HTTP requests without the need of an external, third-party library.
All pom.xml files that had org.apache.httpcomponents in the dependencies no longer have this as a dependency.
All Java files that were using any of the components of the org.apache.httpcomponents.httpClient have been modified to have equivalent code using java.net.http.
=> 988: Replaced all of the Apache HttpClients with Java's java.net.http

spatial-partition/src/test/java/com/iluwatar/spatialpartition/QuadTreeTest.java
Intermittent test failure in Spatial Partition pattern #1001
Tested with repeated test for a sample of 10000 repeatitions to ensure intermittent issue doesn't come again.
- field should exist within the queryrange not other way.
=> Intermittent test failure in Spatial Partition pattern #1001

spatial-partition/src/main/java/com/iluwatar/spatialpartition/Rect.java
#1001 QuadTreeTest was showing intermittent failures. 
The problem was due to the Rect data structure using int to store values (x, y, height, width). 
Since the QuadTree divides its space in four, we need to either to change the Rect data structure or the divide algorithm. 
I find the former more readable and clear.
=> #1001 fix intermittent test failure - changing Rect coordinates to double.

pom.xml
The missing class `PreconditionViolationException` is contained in
`junit-platform-commons` which comes in transitively by this JUnit
version. `junit-jupiter-api` had to be added because
spring-boot-dependencies imports an older version of this dependency.
=> Fixes #1007 by updating JUnit to 5.5.2

circuit-breaker/src/main/java/com/iluwatar/circuitbreaker/App.java, commander/src/main/java/com/iluwatar/commander/Order.java, commander/src/main/java/com/iluwatar/commander/Retry.java, commander/src/main/java/com/iluwatar/commander/Service.java, hexagonal/src/main/java/com/iluwatar/hexagonal/sampledata/SampleData.java, leader-election/src/main/java/com/iluwatar/leaderelection/AbstractInstance.java, master-worker-pattern/src/main/java/com/iluwatar/masterworker/ArrayUtilityMethods.java, priority-queue/src/main/java/com/iluwatar/priority/queue/Worker.java, producer-consumer/src/main/java/com/iluwatar/producer/consumer/Producer.java, retry/src/main/java/com/iluwatar/retry/RetryExponentialBackoff.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/Bubble.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/CellPool.java
Fixed all of the blocking and critical Sonarcloud errors
There were 12 blocking and critical errors in Sonarcloud. They are:
- circuit-breaker/.../com/iluwatar/circuitbreaker/App.java: Add an end condition to this loop
- commander/.../java/com/iluwatar/commander/Order.java: Save and re-use this "Random"
- commander/.../java/com/iluwatar/commander/Retry.java: Save and re-use this "Random"
- commander/.../java/com/iluwatar/commander/Service.java: Save and re-use this "Random"
- hexagonal/.../iluwatar/hexagonal/sampledata/SampleData.java: Save and re-use this "Random"
- leader-election/.../com/iluwatar/leaderelection/AbstractInstance.java: Add an end condition to this loop
- master-worker-pattern/.../java/com/iluwatar/masterworker/ArrayUtilityMethods.java: Save and re-use this "Random"
- …
=> 1010: Fixed all of the blocking and critical Sonarcloud errors

cqrs/pom.xml, eip-aggregator/pom.xml, eip-splitter/pom.xml, eip-wire-tap/pom.xml, trampoline/pom.xml
Remove from child pom not necessary information https://github.com/iluwatar/java-design-patterns/issues/1009 - according to maven dependency management https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management
=> https://github.com/iluwatar/java-design-patterns/issues/1009 - remove child poms overhead information

adapter/src/main/java/com/iluwatar/adapter/App.java, adapter/src/main/java/com/iluwatar/adapter/Captain.java, adapter/src/main/java/com/iluwatar/adapter/FishingBoat.java, adapter/src/main/java/com/iluwatar/adapter/FishingBoatAdapter.java, adapter/src/main/java/com/iluwatar/adapter/package-info.java
=> https://github.com/iluwatar/java-design-patterns/issues/1021 - decrease number of checkstyle errors in adapter pattern

step-builder/src/main/java/com/iluwatar/stepbuilder/App.java, step-builder/src/main/java/com/iluwatar/stepbuilder/Character.java
local variable type inference changes for step builder design pattern
=> local variable type inference changes

pom.xml
Closes #1037 
The license-plugin-header-style.xml in the root directory was not resolved correctly when the project was built from a submodule directory, so I ended up adding a new plugin `directory-maven-plugin` which does that.
Other solutions were to use the `${maven.multiModuleProjectDirectory}` property, but I was not able to make it work, or to add a relative path property to each of the submodules `<properties><projectRoot>${parent.basedir}</projectRoot></properties>`, but this configuration would be difficult to maintain, as there are 120 submodules.
=> #1037: Fix error when building from a submodule directory

ambassador/src/main/java/com/iluwatar/ambassador/App.java, ambassador/src/main/java/com/iluwatar/ambassador/Client.java, ambassador/src/main/java/com/iluwatar/ambassador/RemoteService.java, ambassador/src/main/java/com/iluwatar/ambassador/ServiceAmbassador.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/App.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/AsyncCallback.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/AsyncExecutor.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/AsyncResult.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutor.java, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/AppTest.java, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutorTest.java, balking/src/main/java/com/iluwatar/balking/App.java, balking/src/main/java/com/iluwatar/balking/WashingMachine.java, balking/src/main/java/com/iluwatar/balking/WashingMachineState.java, balking/src/test/java/com/iluwatar/balking/WashingMachineTest.java, bridge/src/main/java/com/iluwatar/bridge/App.java, bridge/src/main/java/com/iluwatar/bridge/Enchantment.java, bridge/src/main/java/com/iluwatar/bridge/FlyingEnchantment.java, bridge/src/main/java/com/iluwatar/bridge/Hammer.java, bridge/src/main/java/com/iluwatar/bridge/SoulEatingEnchantment.java, bridge/src/main/java/com/iluwatar/bridge/Sword.java, bridge/src/main/java/com/iluwatar/bridge/Weapon.java, builder/src/main/java/com/iluwatar/builder/App.java, builder/src/main/java/com/iluwatar/builder/Armor.java, builder/src/main/java/com/iluwatar/builder/HairColor.java, builder/src/main/java/com/iluwatar/builder/HairType.java, builder/src/main/java/com/iluwatar/builder/Hero.java, builder/src/main/java/com/iluwatar/builder/Profession.java, builder/src/main/java/com/iluwatar/builder/Weapon.java
* ambassador
* async-method-invocation
* balking
* bridge
* builder
- java docs
- indentations
=> Resolves checkstyle errors for ambassador, async-method-invocation, balking, bridge, builder

business-delegate/src/main/java/com/iluwatar/business/delegate/App.java, business-delegate/src/main/java/com/iluwatar/business/delegate/BusinessDelegate.java, business-delegate/src/main/java/com/iluwatar/business/delegate/BusinessLookup.java, business-delegate/src/main/java/com/iluwatar/business/delegate/BusinessService.java, business-delegate/src/main/java/com/iluwatar/business/delegate/Client.java, business-delegate/src/main/java/com/iluwatar/business/delegate/EjbService.java, business-delegate/src/main/java/com/iluwatar/business/delegate/JmsService.java, business-delegate/src/main/java/com/iluwatar/business/delegate/ServiceType.java, bytecode/src/main/java/com/iluwatar/bytecode/App.java, bytecode/src/main/java/com/iluwatar/bytecode/Instruction.java, bytecode/src/main/java/com/iluwatar/bytecode/VirtualMachine.java, bytecode/src/main/java/com/iluwatar/bytecode/Wizard.java, bytecode/src/main/java/com/iluwatar/bytecode/util/InstructionConverterUtil.java, caching/src/main/java/com/iluwatar/caching/App.java, caching/src/main/java/com/iluwatar/caching/AppManager.java, caching/src/main/java/com/iluwatar/caching/CacheStore.java, caching/src/main/java/com/iluwatar/caching/CachingPolicy.java, caching/src/main/java/com/iluwatar/caching/DbManager.java, caching/src/main/java/com/iluwatar/caching/LruCache.java, caching/src/main/java/com/iluwatar/caching/UserAccount.java, caching/src/main/java/com/iluwatar/caching/constants/CachingConstants.java
* business-delegate
* bytecode
* caching
- java docs
- indentations
=> Resolves checkstyle errors for business-delegate, bytecode, caching

intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/AbstractFilter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/AddressFilter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/App.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/Client.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/ContactFilter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/DepositFilter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/Filter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/FilterChain.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/FilterManager.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/NameFilter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/Order.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/OrderFilter.java, intercepting-filter/src/main/java/com/iluwatar/intercepting/filter/Target.java, interpreter/src/main/java/com/iluwatar/interpreter/App.java, interpreter/src/main/java/com/iluwatar/interpreter/Expression.java, interpreter/src/main/java/com/iluwatar/interpreter/MinusExpression.java, interpreter/src/main/java/com/iluwatar/interpreter/MultiplyExpression.java, interpreter/src/main/java/com/iluwatar/interpreter/NumberExpression.java, interpreter/src/main/java/com/iluwatar/interpreter/PlusExpression.java, iterator/src/main/java/com/iluwatar/iterator/App.java, iterator/src/main/java/com/iluwatar/iterator/Iterator.java, iterator/src/main/java/com/iluwatar/iterator/bst/BstIterator.java, iterator/src/main/java/com/iluwatar/iterator/bst/TreeNode.java, iterator/src/main/java/com/iluwatar/iterator/list/Item.java, iterator/src/main/java/com/iluwatar/iterator/list/ItemType.java, iterator/src/main/java/com/iluwatar/iterator/list/TreasureChest.java, iterator/src/main/java/com/iluwatar/iterator/list/TreasureChestItemIterator.java
* guarded-suspension
* half-sync-half-async
* hexagonal
- java docs
- indentations
=> Resolves checkstyle errors for intercepting-filter, interpreter, iterator

eip-aggregator/src/main/java/com/iluwatar/eip/aggregator/App.java, eip-aggregator/src/main/java/com/iluwatar/eip/aggregator/routes/AggregatorRoute.java, eip-aggregator/src/main/java/com/iluwatar/eip/aggregator/routes/MessageAggregationStrategy.java, eip-message-channel/src/main/java/com/iluwatar/eip/message/channel/App.java, eip-publish-subscribe/src/main/java/com/iluwatar/eip/publish/subscribe/App.java, eip-splitter/src/main/java/com/iluwatar/eip/splitter/App.java, eip-splitter/src/main/java/com/iluwatar/eip/splitter/routes/SplitterRoute.java, eip-wire-tap/src/main/java/com/iluwatar/eip/wiretap/App.java, eip-wire-tap/src/main/java/com/iluwatar/eip/wiretap/routes/WireTapRoute.java
* eip-aggregator
* eip-message-channel
* eip-publish-subscribe
* eip-splitter
* eip-wire-tap
- java docs
- indentations
=> Resolves checkstyle errors for eip-*

execute-around/src/main/java/com/iluwatar/execute/around/App.java, execute-around/src/main/java/com/iluwatar/execute/around/FileWriterAction.java, execute-around/src/main/java/com/iluwatar/execute/around/SimpleFileWriter.java, extension-objects/src/main/java/App.java, extension-objects/src/main/java/abstractextensions/CommanderExtension.java, extension-objects/src/main/java/abstractextensions/SergeantExtension.java, extension-objects/src/main/java/abstractextensions/SoldierExtension.java, extension-objects/src/main/java/abstractextensions/UnitExtension.java, extension-objects/src/main/java/concreteextensions/Commander.java, extension-objects/src/main/java/concreteextensions/Sergeant.java, extension-objects/src/main/java/concreteextensions/Soldier.java, extension-objects/src/main/java/units/CommanderUnit.java, extension-objects/src/main/java/units/SergeantUnit.java, extension-objects/src/main/java/units/SoldierUnit.java, extension-objects/src/main/java/units/Unit.java
* execute-around
* extension-objects
- java docs
- indentations
=> Resolves checkstyle errors for execute-around extension-objects

template-method/src/main/java/com/iluwatar/templatemethod/App.java, template-method/src/main/java/com/iluwatar/templatemethod/HalflingThief.java, template-method/src/main/java/com/iluwatar/templatemethod/HitAndRunMethod.java, template-method/src/main/java/com/iluwatar/templatemethod/StealingMethod.java, template-method/src/main/java/com/iluwatar/templatemethod/SubtleMethod.java, thread-pool/src/main/java/com/iluwatar/threadpool/App.java, thread-pool/src/main/java/com/iluwatar/threadpool/CoffeeMakingTask.java, thread-pool/src/main/java/com/iluwatar/threadpool/PotatoPeelingTask.java, thread-pool/src/main/java/com/iluwatar/threadpool/Task.java, thread-pool/src/main/java/com/iluwatar/threadpool/Worker.java, throttling/src/main/java/com/iluwatar/throttling/App.java, throttling/src/main/java/com/iluwatar/throttling/B2BService.java, throttling/src/main/java/com/iluwatar/throttling/CallsCount.java, throttling/src/main/java/com/iluwatar/throttling/Tenant.java, throttling/src/main/java/com/iluwatar/throttling/timer/ThrottleTimerImpl.java, throttling/src/main/java/com/iluwatar/throttling/timer/Throttler.java, tls/src/main/java/com/iluwatar/tls/App.java, tls/src/main/java/com/iluwatar/tls/DateFormatCallable.java, tls/src/main/java/com/iluwatar/tls/Result.java, tolerant-reader/src/main/java/com/iluwatar/tolerantreader/App.java, tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFish.java, tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishSerializer.java, tolerant-reader/src/main/java/com/iluwatar/tolerantreader/RainbowFishV2.java
* template-method
* thread-pool
* throttling
* tls
* tolerant-reader
- java docs
- indentations
=> Resolves checkstyle errors for template-method thread-pool throttling tls tolerant-reader

trampoline/src/main/java/com/iluwatar/trampoline/Trampoline.java, trampoline/src/main/java/com/iluwatar/trampoline/TrampolineApp.java, twin/src/main/java/com/iluwatar/twin/App.java, twin/src/main/java/com/iluwatar/twin/BallThread.java, twin/src/main/java/com/iluwatar/twin/GameItem.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/App.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/Candy.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/CandyGame.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/Cell.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/CellPool.java, typeobjectpattern/src/main/java/com/iluwatar/typeobject/JsonParser.java, unit-of-work/src/main/java/com/iluwatar/unitofwork/App.java, unit-of-work/src/main/java/com/iluwatar/unitofwork/IUnitOfWork.java, unit-of-work/src/main/java/com/iluwatar/unitofwork/Student.java, unit-of-work/src/main/java/com/iluwatar/unitofwork/StudentRepository.java, value-object/src/main/java/com/iluwatar/value/object/App.java, value-object/src/main/java/com/iluwatar/value/object/HeroStat.java
* trampoline
* twin
* typeobjectpattern
* unit-of-work
* value-object
- java docs
- indentations
=> Resolves checkstyle errors for trampoline twin typeobjectpattern unit-of-work value-object

ambassador/README.md, ambassador/src/main/java/com/iluwatar/ambassador/Client.java, ambassador/src/main/java/com/iluwatar/ambassador/RemoteService.java, ambassador/src/main/java/com/iluwatar/ambassador/ServiceAmbassador.java, ambassador/src/test/java/com/iluwatar/ambassador/AppTest.java, ambassador/src/test/java/com/iluwatar/ambassador/ClientTest.java, ambassador/src/test/java/com/iluwatar/ambassador/RemoteServiceTest.java, ambassador/src/test/java/com/iluwatar/ambassador/ServiceAmbassadorTest.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/App.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutor.java, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/AppTest.java, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutorTest.java, balking/src/main/java/com/iluwatar/balking/App.java, balking/src/main/java/com/iluwatar/balking/WashingMachine.java, balking/src/test/java/com/iluwatar/balking/AppTest.java, balking/src/test/java/com/iluwatar/balking/WashingMachineTest.java, bridge/src/main/java/com/iluwatar/bridge/App.java, bridge/src/test/java/com/iluwatar/bridge/AppTest.java, bridge/src/test/java/com/iluwatar/bridge/HammerTest.java, bridge/src/test/java/com/iluwatar/bridge/SwordTest.java, bridge/src/test/java/com/iluwatar/bridge/WeaponTest.java, builder/src/main/java/com/iluwatar/builder/App.java, builder/src/main/java/com/iluwatar/builder/Armor.java, builder/src/main/java/com/iluwatar/builder/HairType.java, builder/src/main/java/com/iluwatar/builder/Hero.java, builder/src/test/java/com/iluwatar/builder/AppTest.java, builder/src/test/java/com/iluwatar/builder/HeroTest.java
Migrates:
ambassador
async-method-invocation
balking
bridge
builder
=> Java 11 migration: ambassador async-method-invocation balking bridge builder

twin/src/main/java/com/iluwatar/twin/App.java
Adds a blank in the sentence
> coordinate with each other(via the twin BallThread} class represent the twin objects to coordinate with each other (via the twin reference)
after "other".
Moreover, I capitalized Java.
=> Fixes typo in twin pattern description (in the JavaDocs)

prototype/README.md
You mention in the code example how the protoype pattern can be implemented in Java with the help of Java cloning (i.e. with support of Object.clone()), but then you should also invoke Object.clone.
With the implementation
public Sheep clone() throws CloneNotSupportedException {
return new Sheep(name);
}
it would not be possible (in general) to override clone() in a subclass (e.g. SpecialSheep), because invoking super.clone would return an object of the wrong type, and if we create a new instance of SpecialSheep it is not always possible to copy over the private fields.
This problem can be fixed by using the mechanism provided by Object.clone, i.e. by invoking super.clone(). This creates a shallow copy (which is just fine in this example as the type of the name field (String) is …
=> Changes the description of the prototype pattern

mutex/README.md
=> Fix markdown

naked-objects/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

aggregator-microservices/README.md
Page doesn't exist anymore, so changed to use web archive
Fixes #1161
=> Changing Aggregator Microservices pattern link

leader-election/README.md
Just fix a typo `selec` -> `select`
=> Fix typo for leader-election pattern description

arrange-act-assert/src/test/java/com/iluwatar/arrangeactassert/CashAAATest.java, arrange-act-assert/src/test/java/com/iluwatar/arrangeactassert/CashAntiAAATest.java
Opened for issue https://github.com/iluwatar/java-design-patterns/issues/1462
This PR fixes the assertEquals parameter order in the arrange-act-assert module. 
assertEquals should be expected,  actual. Currently these are reversed and in the incorrect order.
=> Fixes Issue #1462 - Unit Test assertEquals parameters are reversed

pom.xml
Updated ${artifactId} to ${project.artifactId} in parent pom. Usage of ${artifactId} is deprecated.
=> Updated ${artifactId} to ${project.artifactId}

observer/README.md
The log message in the Orcs class should say orcs instead of hobbits.
This is correct in the code example but wrong in the README.
=> Fix typo in README for Observer pattern

.github/workflows/maven-ci.yml, .github/workflows/maven-pr-builder.yml
- PR builder job will not show the build as **failing** anymore in the [readme section badge](https://github.com/iluwatar/java-design-patterns/workflows/Java%20CI%20with%20Maven/badge.svg) for a faulty PR.
- Subsequent builds will be much faster reducing overall build time
- All artifacts from the previous build will be cached and need not be downloaded again for building the code.
- It will update the cache if newer dependencies are added to the **pom** files after completion of the job.
=> updated workflows

pom.xml, subclass-sandbox/pom.xml, subclass-sandbox/src/test/java/com/iluwatar/subclasssandbox/GroundDiveTest.java, subclass-sandbox/src/test/java/com/iluwatar/subclasssandbox/SkyLaunchTest.java
System Lambda is more specific. It only wraps the part of the code that
produces the output.
=> Replace System Rules with System Lambda

.github/workflows/maven-ci.yml
The message on Sonar Cloud displays the warning
> Shallow clone detected during the analysis. Some files will miss SCM information. This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.
=> Configure build to disable shallow clone

event-sourcing/README.md
I saw that some of the links on the [event sourcing page](https://java-design-patterns.com/patterns/event-sourcing/) were broken due to spaces in the markdown between link description and link URL.
This simply removes the spaces to render the URLs correctly.
=> Fix links on the event sourcing page

trampoline/pom.xml, trampoline/src/main/java/com/iluwatar/trampoline/Trampoline.java, trampoline/src/test/java/com/iluwatar/trampoline/TrampolineAppTest.java
- [Build](https://github.com/iluwatar/java-design-patterns/pull/1528/checks?check_run_id=1172522129) failed with below error.
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project trampoline: Compilation failure
Error:  /home/runner/work/java-design-patterns/java-design-patterns/trampoline/src/main/java/com/iluwatar/trampoline/Trampoline.java:[101,9] method does not override or implement a method from a supertype
Error:    (due to <>, every non-private method declared in this anonymous class must override or implement a method from a supertype)
```
- Noticed using JUnit 4 and there is an issue for using JUnit 5.
- Fixed the code to pass the build
- Used JUnit 5
```
[INFO] Running …
```
=> issue 1500 - using JUnit 5 and resolved a build issue

.github/workflows/maven-ci.yml, .github/workflows/maven-pr-builder.yml
⛔ Reopened Pull Request will not start to build automatically
⛔ Labelling and unlabelling them will not start a build
✔️  Opening a new Pull Request.
✔️  Pushing a new commit to existing Pull Request.
=> Update Pull Requests CI trigger behaviour

.gitignore
Tried with Eclipse Java EE 2020-09 on Linux and 2020-12 on Windows platform.
**.checkstyle** files are being tracked which should not be
=> update gitignore for checkstyle

.github/workflows/maven-ci.yml, .github/workflows/maven-pr-builder.yml, .mvn/wrapper/MavenWrapperDownloader.java, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
These files are from Maven wrapper. It works similarly to the Gradle wrapper.
This allows you to run the Maven project without having Maven installed and present on the path. It downloads the correct Maven version if it's not found (as far as I know by default in your user home directory).
The `mvnw` file is for Linux (bash) and the `mvnw.cmd` is for the Windows environment.
Partly addresses #1655
=> #1655: added maven wrapper

.mvn/wrapper/maven-wrapper.properties, pom.xml
To address the build time issue in `master`, this pull request upgrades jacoco library to latest version. See the console log below for error description.
```
Caused by: java.io.IOException: Error while instrumenting javax/script/ScriptEngine.
at org.jacoco.agent.rt.internal_035b120.core.instr.Instrumenter.instrumentError(Instrumenter.java:158)
at org.jacoco.agent.rt.internal_035b120.core.instr.Instrumenter.instrument(Instrumenter.java:108)
at org.jacoco.agent.rt.internal_035b120.CoverageTransformer.transform(CoverageTransformer.java:91)
... 43 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 59
at org.jacoco.agent.rt.internal_035b120.asm.ClassReader.<init>(ClassReader.java:195)
at org.jacoco.agent.rt.internal_035b120.asm.ClassReader.<init>(ClassRead …
```
=> Upgrade jacoco

.circleci/config.yml, .mvn/wrapper/MavenWrapperDownloader.java, mvnw.cmd, parameter-object/pom.xml, parameter-object/src/main/java/com/iluwatar/parameter/object/App.java, parameter-object/src/main/java/com/iluwatar/parameter/object/ParameterObject.java, parameter-object/src/main/java/com/iluwatar/parameter/object/SearchService.java, parameter-object/src/main/java/com/iluwatar/parameter/object/SortOrder.java, parameter-object/src/test/java/com/iluwatar/parameter/object/AppTest.java, parameter-object/src/test/java/com/iluwatar/parameter/object/ParameterObjectTest.java, parameter-object/src/test/java/com/iluwatar/parameter/object/SearchServiceTest.java
This should help run sonar analysis on pull requests from forked repositories as this is our primary source of contributions.
The benefits has already been discussed [here](https://github.com/iluwatar/java-design-patterns/issues/1663#issue-818196974) as it will resolve #1663 
There are a few license format changes that has been amended to this Pull Request as well, which lies beyond the scope of this PR.
=> created CircleCI config for sonar analysis

.github/workflows/maven-ci.yml, .github/workflows/maven-pr-builder.yml
=> Remove labeling trigger for PR and actions set to master

async-method-invocation/README.md, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/App.java
In this pull request
- Make the async method invocation more interesting. We are now firing space rockets and deploying lunar landers.
- Add an explanation and programmatic example
- Completes one small part of issue #590
=> Add explanation to Async Method Invocation pattern

.github/workflows/maven-pr-builder.yml
labeling PR should trigger builds again for all-contributors bot as this is creating a problem.
=> Adding back labelling build triggers to PR

.github/workflows/maven-pr-builder.yml
As labelling is not triggering builds we must revert back to this to avoid unnecessary triggers.
=> task: remove labelling trigger

multiton/pom.xml, multiton/src/test/java/com/iluwatar/multiton/NazgulEnumTest.java
Problem:
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution. In the refactored method, the difference between the assertions lies within different arguments only.
Solution:
Parameterized tests make it possible to run a test multiple times, with different arguments, as individual and independent tests. This way, we were able to make 1 original test with 9 assertions become 9 independent ones, one for each enumeration element. 
Additional change:
Maven dependency concerning the JUnit params library was also added.
=> Improvement: multiple-assertions unit test into parameterized one

double-buffer/README.md
**This Pull request Corresponds to bug #1703**
**Corrected the Double Buffer Pattern Credits Link**
This PR updates the credits URL in Double Buffer Pattern to re-direct to the correct URL .
As a part of this PR , I have edited the `Readme.md` file source for `Credits` section . 
The problem was that it was containing additional braces due to which the URL was not being re-directed to the correct website.
Please could someone review the PR. Thanks.
=> Correcting the Hyperlink to redirect to correct URL.

domain-model/README.md
I noticed that the newly added domain model pattern doesn't show on the website https://java-design-patterns.com. The probable cause for this is the missing language definition from the YAML front matter.
=> Fix domain model not showing on the web site

singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java, singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
Remove unnecessary flag.
Introducing a new static flag to prevent instantiation via reflection is unnecessary. It's been defined as a static variable and therefore it is a shared data, it most likely needs proper synchronization.
besides, I believe it lacks proper readability.
- remove the flag
- check the instance variable to prevent reflection call
=> Remove unnecessary and possibly not threadsafe flag

localization/fr/README.md
Fix typo in french documentation and append a missing semicolon in a &nbsp;
=> Fix typos.

aggregator-microservices/aggregator-service/src/test/java/com/iluwatar/aggregator/microservices/AggregatorTest.java, api-gateway/api-gateway-service/src/test/java/com/iluwatar/api/gateway/ApiGatewayTest.java, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutorTest.java, data-bus/src/test/java/com/iluwatar/databus/DataBusTest.java, pom.xml, serverless/pom.xml, serverless/src/test/java/com/iluwatar/serverless/baas/api/FindPersonApiHandlerTest.java, serverless/src/test/java/com/iluwatar/serverless/baas/api/SavePersonApiHandlerTest.java
This issue fixes #1667
Here is what changed:
- Added JUnit5 libraries for serverless
- Removed the s3 SDK exclusions for serverless dependencies
- Replaced the deprecated `MockitoAnnotations.initMocks(this)` with `MockitoAnnotations.openMocks(this)`
=> #1667: Fixing the serverless tests to use Junit5 and execute

pom.xml
As @iluwatar commented in the issue, I updated Lombok to the latest version. 
The build and the tests still work.
Fixed https://github.com/iluwatar/java-design-patterns/issues/1803
=> Update to the latest Lombok version

cloud-claim-check-pattern/README.md
The new claim check pattern is not visible on java-design-patterns.com. I suspect the reason is that the pattern's frontmatter is missing the language definition. I'm adding it in this pull request.
=> Fix claim check frontmatter

command/src/main/java/com/iluwatar/command/Wizard.java, commander/src/main/java/com/iluwatar/commander/Commander.java, commander/src/test/java/com/iluwatar/commander/CommanderTest.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionBubbles.java
- sonar report :- [here](https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&resolved=false&severities=BLOCKER&types=CODE_SMELL)
- PR raised against issue :- [SonarCloud reports issues #1012](https://github.com/iluwatar/java-design-patterns/issues/1012)
Change description :-
- fixed Sonar blocker and critical issues related to duplicate String literals
- fixed Sonar blocker and critical issues related to duplicate String literals
- removed unnecessary empty default constructor
=> Sonar report - fix blocker and critical ones

reactor/src/main/java/com/iluwatar/reactor/framework/NioReactor.java, reactor/src/main/java/com/iluwatar/reactor/framework/ThreadPoolDispatcher.java
Optimize the closing mode of reactorMain(class: ExecutorService).
Ensure that reactorMain closes on time.
Please see the code.
Reference:
- https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html
=> Optimized NioReactor stop() (Reactor Pattern)

lombok.config, prototype/README.md, prototype/src/main/java/com/iluwatar/prototype/Beast.java, prototype/src/main/java/com/iluwatar/prototype/ElfBeast.java, prototype/src/main/java/com/iluwatar/prototype/ElfMage.java, prototype/src/main/java/com/iluwatar/prototype/ElfWarlord.java, prototype/src/main/java/com/iluwatar/prototype/Mage.java, prototype/src/main/java/com/iluwatar/prototype/OrcBeast.java, prototype/src/main/java/com/iluwatar/prototype/OrcMage.java, prototype/src/main/java/com/iluwatar/prototype/OrcWarlord.java, prototype/src/main/java/com/iluwatar/prototype/Prototype.java, prototype/src/main/java/com/iluwatar/prototype/Warlord.java, prototype/src/test/java/com/iluwatar/prototype/PrototypeTest.java
This PR refactors the Prototype pattern by making it `Cloneable` and thus inheriting the `clone()` method to its subclasses which removes code duplications.
* Fixes [Prototype pattern re-factor #584](https://github.com/iluwatar/java-design-patterns/issues/584)
=> Refactor Prototype pattern (Closes #584)

visitor/README.md, visitor/src/main/java/com/iluwatar/visitor/Commander.java, visitor/src/main/java/com/iluwatar/visitor/CommanderVisitor.java, visitor/src/main/java/com/iluwatar/visitor/Sergeant.java, visitor/src/main/java/com/iluwatar/visitor/SergeantVisitor.java, visitor/src/main/java/com/iluwatar/visitor/Soldier.java, visitor/src/main/java/com/iluwatar/visitor/SoldierVisitor.java, visitor/src/main/java/com/iluwatar/visitor/UnitVisitor.java, visitor/src/test/java/com/iluwatar/visitor/CommanderTest.java, visitor/src/test/java/com/iluwatar/visitor/SergeantTest.java, visitor/src/test/java/com/iluwatar/visitor/SoldierTest.java, visitor/src/test/java/com/iluwatar/visitor/VisitorTest.java
This PR helps for solving #1968 
fix issue 1968 and correct visitor pattern code
Modified issue with visitor mode code, changed different method name to method reload, fixed issue1968.
The main modification of the method in the class is visit, which is accessed only by different parameter types, eliminating some errors and simplifying code writing, in line with the pattern requirements.
=> fix issue 1968 and correct visitor pattern code and test.

pom.xml
Ticket issue : https://github.com/iluwatar/java-design-patterns/issues/2034
Changed the version of Lombok from 1.18.20 to 1.18.22 which will support Java 17 LTS.
=> Updated Lombok version to 1.18.22

acyclic-visitor/pom.xml, acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ConfigureForDosVisitorTest.java, acyclic-visitor/src/test/java/com/iluwatar/acyclicvisitor/ConfigureForUnixVisitorTest.java
Fix #1193. Remove assertj-core from acyclic-visitor to prevent inconsistent library versions
=> Fixed #1193. Remove assertj-core from acyclic-visitor to prevent inconsistent library versions

localization/es/abstract-document/README.md
Translates the abstract-document design pattern's readme file to Spanish. Closes #2045
=> Closes #2045 Translate abstract-document readme to Spanish

pom.xml
This PR aims to solve #2033 by bumping JaCoCo plugin to 0.8.8, as attempting to run `mvn clean install` on the design modules under JDK 17 with the current version will result in the `java.lang.IllegalArgumentException: Unsupported class file major version 61` error.
For testing I've ran an overall `mvn clean install` on the entire project under JDK 17 with source and target also set to 17 in the `pom.xml`, and only the `naked-objects` pattern module produced an error (although there were warnings with other modules). It looks like the problem is rooted in an error running the `Datanucleus` enhancer inside `dom` (not much more error info) and errors inside `integtests` with using versions of the `Cucumber` library that's also too old from the Apache Isis dependency. I've tinkered with it …
=> Upgrade JaCoCo plugin for JDK 17 compatibility (#2033)

localization/zh/README.md
Line 35, the second bracket contains a redundant Chinese character “为”, which should be removed from bracket and put in front of the remain words.
"为" is a preposition, while the meaning of the word in the bracket should be a noun. Anyone who is familar with Chinese will find this problem.
在第35行，第二个网页超链接处，中括号包含了一个多余的汉字“为”。应该将这个汉字移出中括号。
=> A Chinese grammar error in zh version README.md.

.circleci/config.yml
Update Circle CI to use the latest image for OpenJDK 11
closes #2054
=> Use updated image for CircleCI

pom.xml
There are 2 security vulnerabilities found in org.hibernate:hibernate-core 5.2.18.Final
- [CVE-2020-25638](https://www.oscs1024.com/hd/CVE-2020-25638)
- [CVE-2019-14900](https://www.oscs1024.com/hd/CVE-2019-14900)
Upgrade org.hibernate:hibernate-core from 5.2.18.Final to 5.4.24.Final for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.hibernate:hibernate-core to 5.4.24.Final

pom.xml
There are 1 security vulnerabilities found in org.apache.camel:camel-core 2.24.0
- [CVE-2020-11971](https://www.oscs1024.com/hd/CVE-2020-11971)
Upgrade org.apache.camel:camel-core from 2.24.0 to 2.25.1 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.apache.camel:camel-core to 2.25.1

service-layer/src/main/java/com/iluwatar/servicelayer/common/DaoBaseImpl.java, service-layer/src/main/java/com/iluwatar/servicelayer/spell/SpellDaoImpl.java, service-layer/src/main/java/com/iluwatar/servicelayer/spellbook/SpellbookDaoImpl.java, service-layer/src/main/java/com/iluwatar/servicelayer/wizard/WizardDaoImpl.java, service-layer/src/test/java/com/iluwatar/servicelayer/magic/MagicServiceImplTest.java
Remove deprecated method to ease Hibernate upgrade.
Fix the following deprecated method reported by Sonar #1012 in this [link](https://sonarcloud.io/project/issues?fileUuids=AW3G0SexwB6UiZzQNqdf%2CAW3G0SexwB6UiZzQNqdj%2CAW3G0SexwB6UiZzQNqds%2CAW3G0SexwB6UiZzQNqdy&resolved=false&rules=java%3AS1874&id=iluwatar_java-design-patterns).
=> refactoring #1012: Remove deprecated method to ease Hibernate upgrade

cqrs/pom.xml, dirty-flag/pom.xml, eip-aggregator/pom.xml, eip-splitter/pom.xml, eip-wire-tap/pom.xml, layers/src/main/resources/applicationContext.xml, metadata-mapping/pom.xml, naked-objects/dom/pom.xml, page-object/pom.xml, partial-response/pom.xml, pom.xml, repository/src/main/resources/applicationContext.xml, serverless/pom.xml, service-layer/pom.xml
Remove explicit dependencies that are covered by spring-boot-dependencies
hibernate 5.4.24 -> 5.6.12
spring-webmvc 5.0.17 -> 5.3.23
spring-data-jpa 2.0.14 -> 2.7.5
junit 4.12 -> 4.13.2
junit-jupiter 5.7.1 -> 5.8.2
slf4j 1.7.30 -> 1.7.36
logback 1.2.9 -> 1.2.11
jackson 2.12.3 -> 2.13.4
lombok 1.18.22 -> 1.18.24
byte-buddy 1.11.5 -> 1.12.8
jaxb-impl 2.3.2 -> 2.3.7
Fix #978
=> Fix #978: Update spring-boot-dependencies 2.0.9 to 2.7.5

metadata-mapping/README.md, metadata-mapping/src/main/resources/hibernate.cfg.xml, metadata-mapping/src/main/resources/logback.xml
I switched to log level info to suppress logging of hibernate internals by reusing the `logback.xml` from Maven project `cqrs`.
Fix #1929
=> Fix #1929: Suppress logging hibernate internals

metadata-mapping/pom.xml, page-object/pom.xml, page-object/test-automation/pom.xml, page-object/test-automation/src/main/java/com/iluwatar/pageobject/AlbumListPage.java, pom.xml
Resolve maven warning
- Removed duplicated dependency declaration
- Updated `junit-jupiter-api` junit dependency co-ordinates 
=> Fix for maven warnings

factory-kit/README.md
Updated README for the factory-kit pattern.
- As established via Gitter, the README was in fact close to completion.
- Despite the state of the README I made some trivial additions to help users.
- This pattern was outlined in issue #590 and regardless of the status of this PR, the pattern should be removed from the issue given its quality as established on Gitter.
=> Amendments to factory-kit README.md

eip-aggregator/pom.xml, eip-aggregator/src/main/java/com/iluwatar/eip/aggregator/routes/MessageAggregationStrategy.java, eip-aggregator/src/test/java/com/iluwatar/eip/aggregator/routes/MessageAggregationStrategyTest.java, eip-splitter/pom.xml, eip-wire-tap/pom.xml, pom.xml
> Camel 3.17 is the first release where we have official support for Java 17,
https://camel.apache.org/blog/2022/05/camel317-whatsnew/
#2037
=> Upgrade Camel 2.25.1 to 3.18.1

localization/pt/abstract-factory/README.md
I'll translate the readme file of the abstract-factory design pattern to Portuguese and place it under localization.pt.abstract-factory.
=> Translate the abstract factory readme to Portuguese

.circleci/config.yml, .github/workflows/maven-ci.yml, .github/workflows/maven-pr-builder.yml
The naked-objects pattern cannot be build with Java 17 because it use an ancient version of Cucumber.
Fixes #2035
=> Build with Java 17

monitor/src/main/java/com/iluwatar/monitor/Bank.java, monitor/src/main/java/com/iluwatar/monitor/Main.java, monitor/src/test/java/com/iluwatar/monitor/MainTest.java, monitor/src/test/resources/logback.xml
Reduced the logs generated during text execution from over 100 MB to under 4 MB by adjusting the monitor pattern.
I further ensure that the main thread wait until all child threads finished.
Fixes #2369
=> Feat: reduce logs

singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java
- Removed Double-Checked Locking for com.iluwatar.singleton.ThreadSafeLazyLoadedIvoryTower and made it simpler with a Single Check for the instance object.
=> fix: Issue #2459 fixed

localization/es/api-gateway/README.md
Added on /localization/es/ a folder with name api-gateway that contains a README.md file with the translation for api-gateway readme to spanish.
=> docs: Translation of api-gateway readme to Spanish, closes #2472

command/README.md, localization/zh/command/README.md
Fix deques generic type
- Fix README files for command pattern
- Refences to #2462
Description
- Changes the generic type of deques fields in README files from 'Command' to 'Runnable' as in the source code files
=> Fix generic type for deques in command README.md files Ref: #2462

hexagonal/pom.xml, hexagonal/src/test/java/com/iluwatar/hexagonal/banking/MongoBankTest.java, strategy/README.md
- This PR fixes on of the unit tests in the hexagonal design pattern package.
- Issue 2368
- The main changes include an embedded MongoDB in the MongoBank unit test class. The test will spin up this embedded DB before all tests are ran, and will teardown the DB after the runs. The flapdoodle package is used to create this embedded DB. 
=> Issue 2368/fix broken tests

currying/README.md
Genre.FANTAST does not match the Genre enum mentioned in the example, and should be Genre.FANTASY
=> Fix spelling error: Genre.FANTAST

event-sourcing/pom.xml, event-sourcing/src/main/java/com/iluwatar/event/sourcing/app/App.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/event/AccountCreateEvent.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/event/MoneyDepositEvent.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/event/MoneyTransferEvent.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/processor/DomainEventProcessor.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/processor/EventJournal.java, event-sourcing/src/main/java/com/iluwatar/event/sourcing/processor/JsonFileJournal.java, event-sourcing/src/test/java/IntegrationTest.java
Fixing #2445 - Refractor event sourcing
- Removed tight coupling from `DomainEventProcessor` class.
- Switched `Gson` to Jackson `ObjectMapper`.
- Removed deprecated `JsonParser`
- Fixed warnings.
=> Event sourcing 2445

command/README.md
Reference issue: https://github.com/iluwatar/java-design-patterns/issues/2462
This is a trivial change, it updates the README for the command pattern to include the same code as in the implementation. The current README, which uses the "Command" object in the Deque, does not make sense (nor does it compile). Tests and checkstyle pass successfully, as expected.
=> Fix Command pattern README generics

spatial-partition/src/main/java/com/iluwatar/spatialpartition/App.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/Bubble.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/Point.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/QuadTree.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionBubbles.java, spatial-partition/src/main/java/com/iluwatar/spatialpartition/SpatialPartitionGeneric.java
- ConcurrentModificationException
- Wrong log
- Log using formatting anchor
=> [Spatial Partition] (Fix) Issue #2544: Can not run App.java & some logs are wrong

localization/vi/acyclic-visitor/README.md
Add Vietnamese translation of acyclic visitor pattern.
=> [Translate, Vietnamese] (Add) acyclic visitor pattern

localization/ru/abstract-factory/README.md
This pull request localizes the description of the abstract factory design pattern to Russian.
=> Translate Abstract Factory to Russian / Fix #2286 partially

monitor/src/main/java/com/iluwatar/monitor/Bank.java, monitor/src/main/java/com/iluwatar/monitor/Main.java, monitor/src/test/java/com/iluwatar/monitor/BankTest.java
Refactor
* Refactoring the code in monitor pattern that is not reasonable enough
* Modify amount random value origin and bound
* Add getBalance method in Bank class
* Add test for new getBalance method
* Some constants are extracted
It is my first pull request
Have a nice day😁
=> Refactor monitor patterns example code

optimistic-offline-lock/README.md, optimistic-offline-lock/pom.xml, optimistic-offline-lock/src/main/java/com/iluwatar/api/UpdateService.java, optimistic-offline-lock/src/main/java/com/iluwatar/exception/ApplicationException.java, optimistic-offline-lock/src/main/java/com/iluwatar/model/Card.java, optimistic-offline-lock/src/main/java/com/iluwatar/repository/JpaRepository.java, optimistic-offline-lock/src/main/java/com/iluwatar/service/CardUpdateService.java, optimistic-offline-lock/src/test/java/com/iluwatar/OptimisticLockTest.java, pom.xml
=> feature: Add optimistic offline lock (#1306)

master-worker-pattern/README.md
Written up explanation for the Master-Worker pattern.
- Real world example
- Wikipedia says is not available
- Programmatic example using code in the repository
=> Add explanation for master worker pattern

servant/README.md
fix: #2260
modify README.md file.
- add Explanation selection
- add Real-world example, under the Explanation selection. Example express the  the king, queen and servant relationship.
- add plain-word, wiki say
- add programmatic example with code of  king, queen and servant classes.
- add console output by running code at local.
=>  fixed: #2260 Add explanation into README.md for Servant pattern

front-controller/src/main/java/com/iluwatar/front/controller/FrontController.java, role-object/src/main/java/com/iluwatar/roleobject/Role.java
Remove deprecated method of newInstance
Fix the following deprecated method reported by Sonar in [FrontController.java](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1874&id=iluwatar_java-design-patterns&open=AW3G0UZXwB6UiZzQNqjX) and [Role.java](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1874&id=iluwatar_java-design-patterns&open=AW5okyLbklEo66sU7DwF).
=> Remove deprecated method of newInstance

localization/pt/factory/README.md
Translation of the Factory pattern to Portuguese.
- Translation of the factory pattern README to portuguese.
- This translation is part of the #2285 issue.
=> Translate Factory pattern to portuguese.

factory/README.md
Fixed some typos I found in the english factory pattern README.
=> Fix typos for factory pattern README

adapter/README.md, adapter/pom.xml, facade/README.md
Added another tutorial link for the adapter pattern and updated the year in XML file to 2023
=> Added another Tutorial Link in Readme

localization/vi/aggregator-microservices/README.md
I don't know suitable word for `microservice` in our language. But I think we will understand it, like many common words: dev, code, bug,...
=> [Translate, Vietnamese] (Add) aggregator microservices pattern translation #2288

model-view-viewmodel/README.md
- Removed a link  "Learn MVVM"  that takes us to a weird website from the tutorials section in mvvm pattern.
- https://java-design-patterns.com/patterns/model-view-viewmodel/#tutorials
=> removed weird link from mvvm

object-mother/README.md
**Pull Request Title**
Fixed issue #2249 : Added Object Mother Pattern explanation in README.md
**Pull request description**
Here's a detailed explanation of what this fix does:
1. **Objective**:
- The goal of this pull request is to enhance the project's README.md file with an explanation of the Object Mother Pattern in Java.
2. **Content Addition**:
- A new section in the README file is added, explaining the Object Mother Pattern.
- This explanation includes real-world examples, plain language descriptions, and a Java code example for illustration.
3. **Clarity and Accessibility**:
- The added content is designed to be clear and easily understandable, making the Object Mother Pattern more accessible to developers.
4. **Testing and Reliability**:
- Emphasis is placed on the pattern's …
=> Modified Object Mother

.all-contributorsrc, README.md
Fixes https://github.com/iluwatar/java-design-patterns/issues/2229
Updated README.md file of Extension Objects pattern with an explanation. 
The explanation consists of:
- Real world example
- Wikipedia says
- Programmatic example
=> Explanation added to README.md for Extension Objects

localization/it/abstract-document/README.md
Translation of the 'Abstract Document' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Abstract Document' design pattern, which explains the pattern itself.
- Placed the new README.md file in the 'localization/it/abstract-document' directory.
- Provided the link diagram of the class structure in the Italian README.md, ensuring it aligns …
=> translation: translation of abstract document pattern to Italian

localization/it/active-object/README.md
Translation of the 'Active Object' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Active Object' design pattern, which explains the pattern itself.
- Placed the new README.md file in the 'localization/it/active-object' directory.
- Provided the link diagram of the class structure in the Italian README.md, ensuring it aligns with the …
=> translation: translation of active object pattern to Italian

localization/pt/chain-of-responsability/README.md
Translate pattern chain-of-responsability to pt-br (Brazilian portuguese)
=> translate pattern chain-of-responsability to pt-br

localization/it/acyclic-visitor/README.md
Translation of the 'Acyclic Visitor' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Acyclic Visitor' design pattern, which explains the pattern itself.
- Placed the new README.md file in the 'localization/it/acyclic-visitor' directory.
- Provided the link diagram of the class structure in the Italian README.md, ensuring it aligns with …
=> translation: translation of acyclic visitor pattern to Italian

queue-load-leveling/README.md
fix: #2255 
modify README.md file under queue-load-leveling.
- add explanation section
- add plai-word and wiki say
- add programmatic example with code of taskGenerator and ServiceExecutor classes
- add console output by running the code at local
=> fixed: #2255 Add explanation into README.md for Queue-load-leveling pattern

double-buffer/README.md
Fix: #2223 
add into README.md file
- Real world example (computer graphics)
- Wikipedia says
- Programmatic example (double buffer to render a scene)
here the screenshot:
=> fix: #2223 modify README.md file under double-buffer

monad/README.md
Fixes #2245 Explanation for Monad
Updating Monad pattern Readme.md file.
=> Update README.md for monadPattern

localization/it/adapter/README.md
Translation of the 'Adapter' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Adapter' design pattern, which explains the pattern itself.
- Placed the new README.md file in the 'localization/it/adapter' directory.
- Provided the link diagram of the class structure in the Italian README.md, ensuring it aligns with the content of the …
=> translation: translation of adapter pattern to Italian

localization/it/abstract-factory/README.md
Translation of the 'Abstract Factory' pattern README.md into Italian
This pull request adds the Italian translation of the README.md for the 'Abstract Factory' design pattern, which explains the pattern itself.
- Placed the new README.md file in the 'localization/it/abstract-factory' directory.
- Provided the link diagram of the class structure in the Italian README.md, ensuring it aligns with …
=> translation: translation of abstract factory pattern to Italian

dao/src/main/java/com/iluwatar/dao/App.java, dao/src/test/java/com/iluwatar/dao/DbCustomerDaoTest.java, domain-model/src/main/java/com/iluwatar/domainmodel/App.java, layers/src/main/resources/application.properties, repository/src/main/java/com/iluwatar/repository/AppConfig.java, repository/src/main/resources/applicationContext.xml, serialized-entity/README.md, serialized-entity/src/main/java/com/iluwatar/serializedentity/App.java, serialized-entity/src/test/java/com/iluwatar/serializedentity/AppTest.java, table-module/src/main/java/com/iluwatar/tablemodule/App.java, table-module/src/test/java/com/iluwatar/tablemodule/UserTableModuleTest.java, transaction-script/src/main/java/com/iluwatar/transactionscript/App.java, transaction-script/src/test/java/com/iluwatar/transactionscript/HotelDaoImplTest.java, transaction-script/src/test/java/com/iluwatar/transactionscript/HotelTest.java
Fix: [#2366 ](https://github.com/iluwatar/java-design-patterns/issues/2366)
Standardize the use of the h2 database in the project. The in-memory option will not affect the user drive.
Change file-based database usage to in-mem option. I am attaching a screenshot to verify that only h2 db in-mem is used in the project.
=> fix: #2366 Change h2 database usage to in mem

gateway/README.md, pom.xml
- Add to parent `pom.xml`
- Fixes to `README.md`
=> #1297 Gateway pattern fixes

reactor/src/main/java/com/iluwatar/reactor/framework/AbstractNioChannel.java, reactor/src/main/java/com/iluwatar/reactor/framework/NioReactor.java
1. [Refactor] Change 'if' statement to 'Map.computeIfAbsent' in relevant code
2. [Documentation] Polish Javadoc for improved clarity and completeness
=> Polish Javadoc and Using 'Map.computeIfAbsent' instead of 'if' statement

combinator/src/main/java/com/iluwatar/combinator/CombinatorApp.java, combinator/src/test/java/com/iluwatar/combinator/FinderTest.java, combinator/src/test/java/com/iluwatar/combinator/FindersTest.java, composite-view/src/main/java/com/iluwatar/compositeview/AppServlet.java, composite-view/src/test/java/com/iluwatar/compositeview/AppServletTest.java, embedded-value/src/main/java/com/iluwatar/embedded/value/App.java, embedded-value/src/main/java/com/iluwatar/embedded/value/DataSource.java, event-asynchronous/src/main/java/com/iluwatar/event/asynchronous/App.java, metadata-mapping/src/main/java/com/iluwatar/metamapping/utils/DatabaseUtil.java, property/src/test/java/com/iluwatar/property/CharacterTest.java
- Using text blocks wherever necessary instead of escape sequences
- [Issue - 2375](https://github.com/iluwatar/java-design-patterns/issues/2375)
=> Using text blocks instead of String literals

async-method-invocation/README.md, async-method-invocation/etc/async-method-invocation.urm.puml, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/App.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/AsyncCallback.java, async-method-invocation/src/main/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutor.java, async-method-invocation/src/test/java/com/iluwatar/async/method/invocation/ThreadAsyncExecutorTest.java
Eliminate Optional from fields and parameters
This commit addresses the misuse of the Optional class within our Async Method Invocation pattern. Following #2829 , we have removed Optional from being used as class fields and method parameters.
**Key Changes:**
- Class fields previously typed as Optional have been converted to nullable types, with added documentation comments to indicate potential nullability.
- Method parameters that were Optional have been refactored.Removed `Optional<Exception>` from the `onComplete` method parameter of `AsyncCallback` and added an additional `onError(Exception)` method to call when an exception occurs
**Rationale:**
- Enhances serialization compatibility by removing non-serializable Optional fields.
- Reduces code complexity and improves readability by …
=> refactor: Eliminate Optional from fields and parameters for async method invocation

collection-pipeline/README.md, collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/Car.java, collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/FunctionalProgramming.java, collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/ImperativeProgramming.java, collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/Person.java
* Collection Pipeline explanation
* Close #2215
=> Collection pipeline explanation

commander/README.md, commander/src/main/java/com/iluwatar/commander/Commander.java, commander/src/main/java/com/iluwatar/commander/Retry.java, commander/src/main/java/com/iluwatar/commander/employeehandle/EmployeeHandle.java, commander/src/main/java/com/iluwatar/commander/messagingservice/MessagingDatabase.java, commander/src/main/java/com/iluwatar/commander/messagingservice/MessagingService.java, commander/src/main/java/com/iluwatar/commander/paymentservice/PaymentService.java, commander/src/main/java/com/iluwatar/commander/queue/QueueDatabase.java, commander/src/test/java/com/iluwatar/commander/RetryTest.java
=> Commander explanation

double-buffer/README.md, double-buffer/src/main/java/com/iluwatar/doublebuffer/Pixel.java, pom.xml, server-session/README.md, server-session/etc/server-session.urm.puml, server-session/pom.xml, server-session/src/main/java/com/iluwatar/sessionserver/App.java, server-session/src/main/java/com/iluwatar/sessionserver/LoginHandler.java, server-session/src/main/java/com/iluwatar/sessionserver/LogoutHandler.java, server-session/src/test/java/com.iluwatar.sessionserver/LoginHandlerTest.java, server-session/src/test/java/com.iluwatar.sessionserver/LogoutHandlerTest.java
- Add server session to parent pom.xml
- Fix server session checkstyle errors
- Improve double buffer docs
=> Fix server session

double-checked-locking/README.md, double-checked-locking/src/test/java/com/iluwatar/doublechecked/locking/AppTest.java, double-checked-locking/src/test/java/com/iluwatar/doublechecked/locking/InventoryTest.java
=> Explanation for double-checked locking

.all-contributorsrc, localization/vi/builder/README.md
- Add Vietnamese translation of Builder pattern.
- Change my link due to my old domain will expire soon.
=> [Localization] (Add) Vietnamese translation of Builder pattern #2288

version-number/src/main/java/com/iluwatar/versionnumber/BookRepository.java
Currently the version number pattern is not thread safe in case multiple updates are done at the same time. To resolve this I have used ConcurrentHashMap and written the critical code inside the synchronized block with a lock to avoid dirty read and  overwriting.
=> fix: Version number pattern update overwritten #2968

visitor/src/test/java/com/iluwatar/visitor/CommanderVisitorTest.java, visitor/src/test/java/com/iluwatar/visitor/SergeantVisitorTest.java, visitor/src/test/java/com/iluwatar/visitor/SoldierVisitorTest.java, visitor/src/test/java/com/iluwatar/visitor/VisitorTest.java
This PR refactors the VisitorTest class to address code smells related to the misuse of Optional<String> for class fields and constructor parameters. Optional is intended for method return types to indicate "no result," and not for class fields or parameters.
Close #2975
=> fix: Refactored Visitor #2975 

partial-response/src/main/java/com/iluwatar/partialresponse/FieldJsonMapper.java, partial-response/src/main/java/com/iluwatar/partialresponse/Video.java, partial-response/src/test/java/com/iluwatar/partialresponse/VideoResourceTest.java
1. Fixes the issue where Video.toString() outputs an illegal JSON string. All samples should output valid JSON, but in the example below, line 3 is incorrect:
```
17:11:13.976 [main] INFO com.iluwatar.partialresponse.App -- Retrieving full response from server:-
17:11:13.985 [main] INFO com.iluwatar.partialresponse.App -- Get all video information:
17:11:14.014 [main] INFO com.iluwatar.partialresponse.App -- {"id": 1,"title": "Avatar","length": 178,"description": "epic science fiction film","director": "James Cameron","language": "English",}
17:11:14.015 [main] INFO com.iluwatar.partialresponse.App -- ----------------------------------------------------------
17:11:14.015 [main] INFO com.iluwatar.partialresponse.App -- Retrieving partial response from server:-
17:11:14.015 [main] INFO …
```
=> Fix Video.toString() output illegal json and refactor

.github/workflows/maven-ci.yml, .github/workflows/maven-pr-builder.yml
Required for using Node.js 20.x in CI
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md?rgh-link-date=2024-09-04T18%3A38%3A10Z#v400
* Changelog for actions/setup-java@v4 https://github.com/actions/setup-java/releases/tag/v4.0.0
* Changelog for actions/cache@v4 https://github.com/actions/cache/releases/tag/v4.0.0
GitHub Blog post: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> chore: bump github actions to v4

bytecode/src/main/java/com/iluwatar/bytecode/VirtualMachine.java
Updated the bytecode design pattern to the updated switch expression. remove the redundant breaks.
=> updated to switch expression

pom.xml
This PR configures the Maven assembly plugin to build a single fat JAR for each subproject. Each fat JAR follows the naming scheme `${pattern}-${version}-SNAPSHOT.jar`. 
After the Maven Assembly Plugin has been executed, the resulting artifact can be executed as follows:
```bash
$ mvn clean package -DskipTests=true
...
$ cd proxy/target
$ ls -al
drwxr-xr-x  14 patrick  staff     448 Oct  8 00:12 .
drwxr-xr-x   7 patrick  staff     224 Oct  8 00:12 ..
drwxr-xr-x   3 patrick  staff      96 Oct  8 00:12 archive-tmp
-rw-r--r--   1 patrick  staff     846 Oct  8 00:12 checkstyle-cachefile
-rw-r--r--   1 patrick  staff   17646 Oct  8 00:12 checkstyle-checker.xml
-rw-r--r--   1 patrick  staff     696 Oct  8 00:12 checkstyle-result.xml
-rw-r--r--   1 patrick  staff     699 Oct  8 00:12 …
```
=> Include project version in final name

unit-of-work/README.md
There is a typo: `he Unit of Work` was written instead of `The Unit of Work`
=> Update Unit Of Work pattern README file: fix typo

localization/pt/singleton/README.md
**Description:**
Translate the Singleton pattern to Portuguese
**Issue:** 
https://github.com/iluwatar/java-design-patterns/issues/2285
=> translation of the Singleton pattern to Portuguese

singleton/src/main/java/com/iluwatar/singleton/BillPughImplementation.java, singleton/src/main/java/com/iluwatar/singleton/InitializingOnDemandHolderIdiom.java, singleton/src/main/java/com/iluwatar/singleton/IvoryTower.java, singleton/src/test/java/com/iluwatar/singleton/EnumIvoryTowerTest.java, singleton/src/test/java/com/iluwatar/singleton/SingletonTest.java, singleton/src/test/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLockingTest.java
Description:
Fix typo and extend reflection handling for remaining implementations for the Singleton pattern
Issue:
https://github.com/iluwatar/java-design-patterns/issues/3202
=> Fix Singleton typo and extend reflection handling to remaining implementations

anti-corruption-layer/README.md
This PR improves the documentation of the pattern "anti-corruption-layer".
On this PR, I changed the attribute orderInModernSystem type from Optional<LegacyOrder> to Optional<ModernOrder>. Improving the usage example on README.MD.
=> docs: Improve Anti-Corruption-Layer README(#3200)

pom.xml, service-stub/README.md, service-stub/pom.xml, service-stub/src/main/java/com/iluwatar/servicestub/App.java, service-stub/src/main/java/com/iluwatar/servicestub/RealSentimentAnalysisServer.java, service-stub/src/main/java/com/iluwatar/servicestub/SentimentAnalysisServer.java, service-stub/src/main/java/com/iluwatar/servicestub/StubSentimentAnalysisServer.java, service-stub/src/test/java/com/iluwatar/servicestub/AppTest.java, service-stub/src/test/java/com/iluwatar/servicestub/RealSentimentAnalysisServerTest.java, service-stub/src/test/java/com/iluwatar/servicestub/StubSentimentAnalysisServerTest.java
This PR introduces the Service Stub Pattern, demonstrated through a Sentiment Analysis example.
- Adds SentimentAnalysisServer interface.
- Implements RealSentimentAnalysisServer, simulating random sentiment results with delay.
- Implements StubSentimentAnalysisServer, providing predictable, input-based outputs.
- Includes unit tests and full documentation.
Fixes #381.
=> Add Service Stub Pattern using Sentiment Analysis example

leader-followers/src/main/java/com/iluwatar/leaderfollowers/App.java
Adds a missing license header to an existing file. This was done by running: `./mvnw license:format`
=> chore: adding missing license
